defmodule DevIDE.Terminals.ToolThemes do
  @moduledoc """
  Renders registry-declared TUI tool theme configs so tools follow the DevIDE
  terminal theme without hand-managed dotfiles.

  Independence-first: prefer `:static` scheme-AGNOSTIC indexed-color configs
  (the per-viewer browser LUT does the actual theming), and fall back to
  `:scheme_variant` stamping only for tools whose themes cannot be expressed
  with indexed colors (grok).

  `:static` files carry a marker as their first line; a marker-less file is
  treated as user-managed and never touched. `:scheme_variant` files are
  user-owned — only the single registry-declared key is stamped and all other
  content is preserved byte-for-byte. Those targets are box-global (e.g.
  `~/.grok/config.toml` is shared by every workspace on the host and hot-reloaded
  by grok); a draining deploy instance must not re-stamp them — see
  `DevIDE.Deployment.Drain.guard_shared_write/1`.
  """

  require Logger

  alias DevIDE.Terminals.Shims
  alias DevIDE.Terminals.Theme

  @marker "# Generated by DevIDE.Terminals.ToolThemes — delete this line to manage this file yourself."

  @templates (for {_name, %{mode: :static, template: rel}} <- Shims.theme_specs(), into: %{} do
                path = Path.expand(Path.join("priv", rel))
                @external_resource path
                {rel, File.read!(path)}
              end)

  @doc "Marker line stamped as line 1 of DevIDE-managed static theme files."
  @spec marker() :: String.t()
  def marker, do: @marker

  @doc """
  Ensures every registry-declared tool theme matches `scheme`.

  Per-tool failures are rescued and logged (once per unique failure); always
  returns `:ok`. No-op unless `:tool_themes_enabled` (default `true`).
  """
  @spec ensure_all(Theme.scheme()) :: :ok
  def ensure_all(scheme) when scheme in [:dark, :light] do
    if enabled?() do
      Enum.each(Shims.theme_specs(), fn {name, theme_spec} ->
        case safe_ensure(name, theme_spec, scheme) do
          {:error, reason} -> log_failure(name, reason)
          _ok_or_skipped -> :ok
        end
      end)
    end

    :ok
  end

  @doc "Ensures a single tool theme file matches its registry descriptor for `scheme`."
  @spec ensure(String.t(), Shims.theme_spec(), Theme.scheme()) ::
          :ok | {:skipped, :user_managed} | {:error, term()}
  def ensure(name, %{mode: :static} = theme_spec, scheme)
      when is_binary(name) and scheme in [:dark, :light] do
    ensure_static(name, theme_spec, scheme)
  end

  def ensure(name, %{mode: :scheme_variant} = theme_spec, scheme)
      when is_binary(name) and scheme in [:dark, :light] do
    ensure_scheme_variant(name, theme_spec, scheme)
  end

  @doc false
  @spec reset_memo!() :: :ok
  def reset_memo! do
    Enum.each(Shims.theme_specs(), fn {name, _theme_spec} ->
      :persistent_term.erase(memo_key(name))
      :persistent_term.erase(failure_key(name))
    end)

    :ok
  end

  # Target paths come from the compile-time registry expanded against
  # operator/app configuration, not web input.
  # sobelow_skip ["Traversal.FileModule"]
  defp ensure_static(name, %{path: path, template: template_rel}, scheme) do
    desired = @templates |> Map.fetch!(template_rel) |> with_marker()
    target = expand_path(path)
    hash = :erlang.phash2({target, scheme, desired})

    with nil <- memoized_result(name, hash, target) do
      case File.read(target) do
        {:error, :enoent} ->
          write!(target, desired)
          memoize(name, hash, desired, :ok)

        {:ok, ^desired} ->
          memoize(name, hash, desired, :ok)

        {:ok, existing} ->
          if first_line(existing) == @marker do
            write!(target, desired)
            memoize(name, hash, desired, :ok)
          else
            memoize(name, hash, existing, {:skipped, :user_managed})
          end

        {:error, reason} ->
          {:error, reason}
      end
    end
  end

  # Target paths come from the compile-time registry expanded against
  # operator/app configuration, not web input.
  # sobelow_skip ["Traversal.FileModule"]
  defp ensure_scheme_variant(name, theme_spec, scheme) do
    case DevIDE.Deployment.Drain.guard_shared_write(fn -> :write end) do
      :noop ->
        :ok

      _ ->
        do_ensure_scheme_variant(name, theme_spec, scheme)
    end
  end

  # Target paths come from the compile-time registry expanded against
  # operator/app configuration, not web input.
  # sobelow_skip ["Traversal.FileModule"]
  defp do_ensure_scheme_variant(name, %{path: path, stamp: stamp}, scheme) do
    %{format: :toml, section: section, key: key, values: values} = stamp
    value = Map.fetch!(values, scheme)
    target = expand_path(path)
    hash = :erlang.phash2({target, scheme, value})

    with nil <- memoized_result(name, hash, target) do
      case File.read(target) do
        {:error, :enoent} ->
          stamped = stamp_toml(nil, section, key, value)
          write!(target, stamped)
          memoize(name, hash, stamped, :ok)

        {:ok, existing} ->
          content =
            case stamp_toml(existing, section, key, value) do
              ^existing ->
                existing

              stamped ->
                write!(target, stamped)
                stamped
            end

          memoize(name, hash, content, :ok)

        {:error, reason} ->
          {:error, reason}
      end
    end
  end

  @doc false
  @spec stamp_toml(String.t() | nil, String.t(), String.t(), String.t()) :: String.t()
  def stamp_toml(nil, section, key, value) do
    "[#{section}]\n#{key} = \"#{value}\"\n"
  end

  def stamp_toml(content, section, key, value) when is_binary(content) do
    lines = String.split(content, "\n")
    header = "[#{section}]"
    stamped = "#{key} = \"#{value}\""

    case Enum.find_index(lines, &(String.trim(&1) == header)) do
      nil ->
        content <> "\n[#{section}]\n#{key} = \"#{value}\"\n"

      header_index ->
        key_pattern = ~r/^\s*#{Regex.escape(key)}\s*=/
        section_end = section_end_index(lines, header_index)

        key_index =
          Enum.find(
            (header_index + 1)..(section_end - 1)//1,
            &Regex.match?(key_pattern, Enum.at(lines, &1))
          )

        lines =
          case key_index do
            nil -> List.insert_at(lines, header_index + 1, stamped)
            index -> List.replace_at(lines, index, stamped)
          end

        Enum.join(lines, "\n")
    end
  end

  defp section_end_index(lines, header_index) do
    lines
    |> Enum.with_index()
    |> Enum.find_value(length(lines), fn {line, index} ->
      trimmed = String.trim(line)

      if index > header_index and String.starts_with?(trimmed, "[") and
           String.ends_with?(trimmed, "]"),
         do: index
    end)
  end

  defp with_marker(template) do
    if first_line(template) == @marker do
      template
    else
      @marker <> "\n" <> template
    end
  end

  defp first_line(content) do
    content |> String.split("\n", parts: 2) |> hd()
  end

  # Written paths are registry-declared and expanded against operator/app
  # configuration, not web input.
  # sobelow_skip ["Traversal.FileModule"]
  defp write!(path, content) do
    File.mkdir_p!(Path.dirname(path))
    tmp = path <> ".tmp-" <> Integer.to_string(System.unique_integer([:positive]))

    try do
      File.write!(tmp, content)
      File.chmod!(tmp, 0o644)
      File.rename!(tmp, path)
    after
      if File.exists?(tmp), do: File.rm(tmp)
    end

    :ok
  end

  defp expand_path("~/" <> rest), do: Path.join(theme_home(), rest)
  defp expand_path("~"), do: theme_home()
  defp expand_path(path), do: Path.expand(path)

  defp theme_home do
    Application.get_env(:dev_ide, :tool_theme_home) ||
      System.get_env("HOME") ||
      raise "cannot expand tool theme path: no :tool_theme_home config and no $HOME"
  end

  defp enabled? do
    Application.get_env(:dev_ide, :tool_themes_enabled, true)
  end

  defp safe_ensure(name, theme_spec, scheme) do
    ensure(name, theme_spec, scheme)
  rescue
    error -> {:error, error}
  end

  # The memo stores `{desired_hash, content_hash, result}`: the result is only
  # trusted while the on-disk bytes still hash to the content that was last
  # verified. Hashing the bytes the verify path actually read or wrote — not a
  # stat taken afterwards — means an external rewrite misses the memo even when
  # it lands in the same second with the same size, or between verify and
  # memoize, so managed drift is restored within the same BEAM lifetime, not
  # just after restarts.
  # sobelow_skip ["Traversal.FileModule"]
  defp memoized_result(name, hash, target) do
    with {^hash, content_hash, result} <- :persistent_term.get(memo_key(name), nil),
         {:ok, content} <- File.read(target),
         ^content_hash <- content_hash(content) do
      result
    else
      _ -> nil
    end
  end

  defp memoize(name, hash, content, result) do
    :persistent_term.put(memo_key(name), {hash, content_hash(content), result})
    result
  end

  defp content_hash(content), do: :crypto.hash(:sha256, content)

  # Logs once per unique failure per tool; repeated identical failures on
  # every pane spawn or scheme change would otherwise flood the log.
  defp log_failure(name, reason) do
    key = failure_key(name)
    hash = :erlang.phash2(reason)

    if :persistent_term.get(key, nil) != hash do
      :persistent_term.put(key, hash)
      Logger.warning("tool theme provisioning failed for #{name}: #{inspect(reason)}")
    end
  end

  defp memo_key(name), do: {__MODULE__, name}
  defp failure_key(name), do: {__MODULE__, :failed, name}
end
