# sobelow_skip ["Traversal.FileModule"]
defmodule DevIDE.Agents.MCPMaterializer do
  @moduledoc false

  alias DevIDE.Agents.MCPUrls

  @doc """
  Write per-workspace MCP client configs for external agents.

  Mirrors `scripts/materialize-agent-mcp.sh` so the release can materialize
  configs without shelling out to the checkout.
  """
  @spec materialize(map(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def materialize(workspace, opts \\ []) when is_map(workspace) do
    with {:ok, token} <- api_token(),
         {:ok, staging} <- staging_home(workspace, opts) do
      urls = mcp_urls(workspace)
      checkout = Keyword.get(opts, :checkout) || workspace[:path] || workspace["path"]
      :ok = File.mkdir_p(Path.join(staging, "grok"))
      :ok = File.mkdir_p(Path.join(staging, "codex"))
      :ok = File.mkdir_p(Path.join(staging, "cursor"))

      :ok = write_grok_config(staging, urls, token)
      :ok = write_codex_config(staging, urls)
      :ok = write_opencode_config(staging, urls)
      :ok = write_mcp_json(staging, urls, token)
      :ok = write_env_sh(staging, workspace, urls, token, checkout)

      maybe_copy_to_checkout(staging, checkout)

      {:ok, staging}
    end
  end

  defp api_token do
    case api_token_value() do
      nil -> {:error, :api_token_missing}
      token -> {:ok, token}
    end
  end

  defp api_token_value do
    Application.get_env(:dev_ide, :api_token) ||
      non_empty_env("DEV_IDE_API_TOKEN")
  end

  defp non_empty_env(name) do
    case System.get_env(name) do
      value when is_binary(value) and value != "" -> value
      _ -> nil
    end
  end

  defp staging_home(workspace, opts) do
    workspace_name = workspace_name(workspace)

    staging =
      Keyword.get(opts, :staging_home) ||
        non_empty_env("DEVIDE_AGENT_MCP_HOME") ||
        Path.join([home_dir(), ".devide", "agent-mcp", workspace_name])

    {:ok, staging}
  rescue
    e in [ArgumentError] -> {:error, e}
  end

  defp home_dir do
    System.get_env("HOME") ||
      raise ArgumentError, "HOME is required to materialize agent MCP configs"
  end

  defp workspace_name(workspace) do
    Map.get(workspace, :name) || Map.get(workspace, "name") ||
      Map.get(workspace, :id) || Map.get(workspace, "id") ||
      "workspace"
  end

  defp workspace_id(workspace) do
    Map.get(workspace, :id) || Map.get(workspace, "id")
  end

  defp mcp_urls(workspace) do
    id = workspace_id(workspace)

    %{
      terminal: MCPUrls.terminal_url(id),
      preview: MCPUrls.preview_url(id)
    }
  end

  defp write_grok_config(staging, urls, _token) do
    content = """
    # Generated by DevIDE.Agents.MCPMaterializer — do not edit by hand.
    [mcp_servers.devide-terminal]
    url = "#{urls.terminal}"
    enabled = true

    [mcp_servers.devide-terminal.headers]
    Authorization = "Bearer ${DEV_IDE_API_TOKEN}"

    [mcp_servers.devide-preview]
    url = "#{urls.preview}"
    enabled = true

    [mcp_servers.devide-preview.headers]
    Authorization = "Bearer ${DEV_IDE_API_TOKEN}"
    """

    write_file(Path.join(staging, "grok/config.toml"), content)
  end

  defp write_codex_config(staging, urls) do
    content = """
    # Generated by DevIDE.Agents.MCPMaterializer — do not edit by hand.
    [mcp_servers.devide-terminal]
    url = "#{urls.terminal}"
    enabled = true
    bearer_token_env_var = "DEV_IDE_API_TOKEN"

    [mcp_servers.devide-preview]
    url = "#{urls.preview}"
    enabled = true
    bearer_token_env_var = "DEV_IDE_API_TOKEN"
    """

    write_file(Path.join(staging, "codex/config.toml"), content)
  end

  defp write_opencode_config(staging, urls) do
    payload = %{
      "$schema" => "https://opencode.ai/config.json",
      "mcp" => %{
        "devide-terminal" => %{
          "type" => "remote",
          "url" => urls.terminal,
          "enabled" => true,
          "oauth" => false,
          "headers" => %{"Authorization" => "Bearer {env:DEV_IDE_API_TOKEN}"}
        },
        "devide-preview" => %{
          "type" => "remote",
          "url" => urls.preview,
          "enabled" => true,
          "oauth" => false,
          "headers" => %{"Authorization" => "Bearer {env:DEV_IDE_API_TOKEN}"}
        }
      }
    }

    write_file(Path.join(staging, "opencode.json"), Jason.encode!(payload, pretty: true) <> "\n")
  end

  defp write_mcp_json(staging, urls, token) do
    bearer = "Bearer #{sanitize_token(token)}"

    payload = %{
      "mcpServers" => %{
        "devide-terminal" => %{
          "type" => "http",
          "url" => urls.terminal,
          "headers" => %{"Authorization" => bearer}
        },
        "devide-preview" => %{
          "type" => "http",
          "url" => urls.preview,
          "headers" => %{"Authorization" => bearer}
        }
      }
    }

    json = Jason.encode!(payload, pretty: true) <> "\n"
    :ok = write_file(Path.join(staging, ".mcp.json"), json)
    write_file(Path.join(staging, "cursor/mcp.json"), json)
  end

  defp write_env_sh(staging, workspace, urls, token, checkout) do
    workspace_id = workspace_id(workspace)
    workspace_name = workspace_name(workspace)
    env_sh = Path.join(staging, "env.sh")
    scripts = if checkout != "", do: Path.join(checkout, "scripts"), else: ""

    content = """
    # Generated by DevIDE.Agents.MCPMaterializer
    export DEV_IDE_API_TOKEN='#{token}'
    export DEVIDE_WORKSPACE_ID='#{workspace_id}'
    export DEVIDE_WORKSPACE_NAME='#{workspace_name}'
    export DEVIDE_TERMINAL_MCP_URL='#{urls.terminal}'
    export DEVIDE_PREVIEW_MCP_URL='#{urls.preview}'
    export DEVIDE_CHECKOUT='#{checkout}'
    export DEVIDE_AGENT_MCP_HOME='#{staging}'
    export DEVIDE_SCRIPTS='#{scripts}'
    export DEVIDE_AGENT_ENV_FILE='#{env_sh}'
    export PATH="${HOME}/.local/bin:${PATH}"
    """

    write_file(env_sh, content)
    File.chmod(env_sh, 0o600)
    :ok
  end

  defp maybe_copy_to_checkout(staging, checkout) when is_binary(checkout) and checkout != "" do
    if File.dir?(checkout) do
      checkout_mcp = Path.join(checkout, ".mcp.json")
      checkout_cursor_dir = Path.join(checkout, ".cursor")
      checkout_cursor_mcp = Path.join(checkout_cursor_dir, "mcp.json")

      :ok = File.mkdir_p(checkout_cursor_dir)
      :ok = File.cp(Path.join(staging, ".mcp.json"), checkout_mcp)
      :ok = File.cp(Path.join(staging, "cursor/mcp.json"), checkout_cursor_mcp)
      :ok = File.chmod(checkout_mcp, 0o600)
      File.chmod(checkout_cursor_mcp, 0o600)
    end

    :ok
  end

  defp maybe_copy_to_checkout(_staging, _checkout), do: :ok

  defp write_file(path, content) do
    path |> Path.dirname() |> File.mkdir_p()
    File.write!(path, content)
    :ok
  end

  defp sanitize_token(token) when is_binary(token) do
    token = String.trim(token)

    case token do
      <<q, rest::binary>> when q in [?\', ?\"] ->
        size = byte_size(rest)

        if size > 0 and :binary.last(rest) == q do
          :binary.part(rest, 0, size - 1)
        else
          token
        end

      _ ->
        token
    end
  end
end
