defmodule DevIDE.Agents.MCPMaterializer do
  @moduledoc """
  Writes per-workspace MCP client config files (Grok, Codex, opencode, Cursor,
  `.mcp.json`, `env.sh`) into a staging home so external agents connect to the
  DevIDE terminal/preview/Tidewave MCP endpoints with the right bearer token.
  """

  alias DevIDE.Agents.{MCPUrls, TidewaveMCP}

  @doc """
  Write per-workspace MCP client configs for external agents.

  Mirrors `scripts/materialize-agent-mcp.sh` so the release can materialize
  configs without shelling out to the checkout.
  """
  @spec materialize(map(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def materialize(workspace, opts \\ []) when is_map(workspace) do
    with {:ok, token} <- api_token(),
         {:ok, staging} <- staging_home(workspace, opts) do
      urls = mcp_urls(workspace, opts)
      checkout = Keyword.get(opts, :checkout) || workspace[:path] || workspace["path"]
      :ok = ensure_staging_dirs(staging)

      :ok = write_grok_config(staging, urls, workspace)
      :ok = write_codex_config(staging, urls, workspace)
      :ok = write_opencode_config(staging, urls, workspace)
      :ok = write_mcp_json(staging, urls, token, workspace)
      :ok = write_env_sh(staging, workspace, urls, token, checkout)

      maybe_copy_to_checkout(staging, checkout)

      {:ok, staging}
    end
  end

  # sobelow_skip ["Traversal.FileModule"]
  defp ensure_staging_dirs(staging) do
    :ok = File.mkdir_p(Path.join(staging, "grok"))
    :ok = File.mkdir_p(Path.join(staging, "codex"))
    File.mkdir_p(Path.join(staging, "cursor"))
  end

  defp api_token do
    case api_token_value() do
      nil -> {:error, :api_token_missing}
      token -> {:ok, token}
    end
  end

  defp api_token_value do
    Application.get_env(:dev_ide, :api_token) ||
      non_empty_env("DEV_IDE_API_TOKEN")
  end

  defp non_empty_env(name) do
    case System.get_env(name) do
      value when is_binary(value) and value != "" -> value
      _ -> nil
    end
  end

  defp staging_home(workspace, opts) do
    workspace_name = workspace_name(workspace)

    staging =
      Keyword.get(opts, :staging_home) ||
        non_empty_env("DEVIDE_AGENT_MCP_HOME") ||
        Path.join([home_dir(), ".devide", "agent-mcp", workspace_name])

    {:ok, staging}
  rescue
    e in [ArgumentError] -> {:error, e}
  end

  defp home_dir do
    System.get_env("HOME") ||
      raise ArgumentError, "HOME is required to materialize agent MCP configs"
  end

  defp workspace_name(workspace) do
    Map.get(workspace, :name) || Map.get(workspace, "name") ||
      Map.get(workspace, :id) || Map.get(workspace, "id") ||
      "workspace"
  end

  defp workspace_id(workspace) do
    Map.get(workspace, :id) || Map.get(workspace, "id")
  end

  defp mcp_urls(workspace, opts) do
    id = workspace_id(workspace)
    tidewave = TidewaveMCP.resolve_url(workspace, opts)

    %{
      terminal: MCPUrls.terminal_url(id),
      preview: MCPUrls.preview_url(id),
      tidewave: tidewave,
      tidewave_key: if(tidewave, do: TidewaveMCP.server_key(workspace), else: nil)
    }
  end

  defp write_grok_config(staging, urls, workspace) do
    {terminal_key, preview_key} = server_keys(workspace)

    content = """
    # Generated by DevIDE.Agents.MCPMaterializer — do not edit by hand.
    [mcp_servers.#{terminal_key}]
    url = "#{urls.terminal}"
    enabled = true

    [mcp_servers.#{terminal_key}.headers]
    Authorization = "Bearer ${DEV_IDE_API_TOKEN}"

    [mcp_servers.#{preview_key}]
    url = "#{urls.preview}"
    enabled = true

    [mcp_servers.#{preview_key}.headers]
    Authorization = "Bearer ${DEV_IDE_API_TOKEN}"
    #{tidewave_grok_block(urls)}
    """

    write_file(Path.join(staging, "grok/config.toml"), content)
  end

  defp write_codex_config(staging, urls, workspace) do
    {terminal_key, preview_key} = server_keys(workspace)

    content = """
    # Generated by DevIDE.Agents.MCPMaterializer — do not edit by hand.
    [mcp_servers.#{terminal_key}]
    url = "#{urls.terminal}"
    enabled = true
    bearer_token_env_var = "DEV_IDE_API_TOKEN"

    [mcp_servers.#{preview_key}]
    url = "#{urls.preview}"
    enabled = true
    bearer_token_env_var = "DEV_IDE_API_TOKEN"
    #{tidewave_codex_block(urls)}
    """

    write_file(Path.join(staging, "codex/config.toml"), content)
  end

  defp write_opencode_config(staging, urls, workspace) do
    {terminal_key, preview_key} = server_keys(workspace)

    mcp =
      %{
        terminal_key => %{
          "type" => "remote",
          "url" => urls.terminal,
          "enabled" => true,
          "oauth" => false,
          "headers" => %{"Authorization" => "Bearer {env:DEV_IDE_API_TOKEN}"}
        },
        preview_key => %{
          "type" => "remote",
          "url" => urls.preview,
          "enabled" => true,
          "oauth" => false,
          "headers" => %{"Authorization" => "Bearer {env:DEV_IDE_API_TOKEN}"}
        }
      }
      |> Map.merge(tidewave_opencode_entries(urls))

    payload = %{
      "$schema" => "https://opencode.ai/config.json",
      "mcp" => mcp
    }

    write_file(Path.join(staging, "opencode.json"), Jason.encode!(payload, pretty: true) <> "\n")
  end

  defp write_mcp_json(staging, urls, _token, workspace) do
    {terminal_key, preview_key} = server_keys(workspace)
    bearer = "Bearer ${DEV_IDE_API_TOKEN}"

    servers =
      %{
        terminal_key => %{
          "type" => "http",
          "url" => urls.terminal,
          "headers" => %{"Authorization" => bearer}
        },
        preview_key => %{
          "type" => "http",
          "url" => urls.preview,
          "headers" => %{"Authorization" => bearer}
        }
      }
      |> Map.merge(tidewave_mcp_json_entries(urls))

    payload = %{"mcpServers" => servers}

    json = Jason.encode!(payload, pretty: true) <> "\n"
    :ok = write_file(Path.join(staging, ".mcp.json"), json)
    write_file(Path.join(staging, "cursor/mcp.json"), json)
  end

  defp server_keys(workspace) do
    slug =
      workspace
      |> workspace_name()
      |> String.replace(~r/[^a-zA-Z0-9]+/, "-")
      |> String.trim("-")
      |> String.downcase()

    slug = if slug == "", do: "workspace", else: slug
    {"devide-terminal-#{slug}", "devide-preview-#{slug}"}
  end

  # sobelow_skip ["Traversal.FileModule"]
  defp write_env_sh(staging, workspace, urls, token, checkout) do
    workspace_id = workspace_id(workspace)
    workspace_name = workspace_name(workspace)
    env_sh = Path.join(staging, "env.sh")
    scripts = if checkout != "", do: Path.join(checkout, "scripts"), else: ""

    content = """
    # Generated by DevIDE.Agents.MCPMaterializer
    export DEV_IDE_API_TOKEN='#{sanitize_token(token)}'
    export DEVIDE_WORKSPACE_ID='#{workspace_id}'
    export DEVIDE_WORKSPACE_NAME='#{workspace_name}'
    export DEVIDE_TERMINAL_MCP_URL='#{urls.terminal}'
    export DEVIDE_PREVIEW_MCP_URL='#{urls.preview}'
    #{tidewave_env_export(urls)}
    export DEVIDE_CHECKOUT='#{checkout}'
    export DEVIDE_AGENT_MCP_HOME='#{staging}'
    export DEVIDE_SCRIPTS='#{scripts}'
    export DEVIDE_AGENT_ENV_FILE='#{env_sh}'
    export PATH="${HOME}/.local/bin:${PATH}"
    """

    write_file(env_sh, content)
    File.chmod(env_sh, 0o600)
    :ok
  end

  # sobelow_skip ["Traversal.FileModule"]
  defp maybe_copy_to_checkout(staging, checkout) when is_binary(checkout) and checkout != "" do
    if File.dir?(checkout) do
      # Claude reads its workspace-isolated staging `.mcp.json` via
      # `claude --mcp-config` (see scripts/launch-devide-agent.sh); only Cursor
      # needs a file in the checkout. Copying `.mcp.json` here previously made a
      # shared checkout accumulate every workspace's servers, so it is omitted.
      checkout_cursor_dir = Path.join(checkout, ".cursor")
      checkout_cursor_mcp = Path.join(checkout_cursor_dir, "mcp.json")

      :ok = File.mkdir_p(checkout_cursor_dir)
      :ok = File.cp(Path.join(staging, "cursor/mcp.json"), checkout_cursor_mcp)
      File.chmod(checkout_cursor_mcp, 0o600)
    end

    :ok
  end

  defp maybe_copy_to_checkout(_staging, _checkout), do: :ok

  # sobelow_skip ["Traversal.FileModule"]
  defp write_file(path, content) do
    path |> Path.dirname() |> File.mkdir_p()
    File.write!(path, content)
    :ok
  end

  defp tidewave_grok_block(%{tidewave: url, tidewave_key: key})
       when is_binary(url) and is_binary(key) do
    """

    [mcp_servers.#{key}]
    url = "#{url}"
    enabled = true
    """
  end

  defp tidewave_grok_block(_), do: ""

  defp tidewave_codex_block(%{tidewave: url, tidewave_key: key})
       when is_binary(url) and is_binary(key) do
    """

    [mcp_servers.#{key}]
    url = "#{url}"
    enabled = true
    """
  end

  defp tidewave_codex_block(_), do: ""

  defp tidewave_opencode_entries(%{tidewave: url, tidewave_key: key})
       when is_binary(url) and is_binary(key) do
    %{
      key => %{
        "type" => "remote",
        "url" => url,
        "enabled" => true,
        "oauth" => false
      }
    }
  end

  defp tidewave_opencode_entries(_), do: %{}

  defp tidewave_mcp_json_entries(%{tidewave: url, tidewave_key: key})
       when is_binary(url) and is_binary(key) do
    %{key => %{"type" => "http", "url" => url}}
  end

  defp tidewave_mcp_json_entries(_), do: %{}

  defp tidewave_env_export(%{tidewave: url}) when is_binary(url) do
    "export DEVIDE_TIDEWAVE_MCP_URL='#{url}'"
  end

  defp tidewave_env_export(_), do: ""

  defp sanitize_token(token) when is_binary(token) do
    token = String.trim(token)

    case token do
      <<q, rest::binary>> when q in [?\', ?\"] ->
        size = byte_size(rest)

        if size > 0 and :binary.last(rest) == q do
          :binary.part(rest, 0, size - 1)
        else
          token
        end

      _ ->
        token
    end
  end
end
