defmodule DevIDE.Agents.MCPMaterializer do
  @moduledoc """
  Writes per-workspace MCP client config files (Grok, Codex, opencode, Cursor,
  `.mcp.json`, `env.sh`) into a staging home so external agents connect to the
  DevIDE terminal/preview/artifact/Tidewave MCP endpoints with the right bearer
  token.
  """

  alias DevIDE.Agents.{AgentShims, AuthProfile, MCPUrls, TidewaveMCP, WorkspaceTokens}

  @doc """
  Write per-workspace MCP client configs for external agents.

  Mirrors `scripts/materialize-agent-mcp.sh` so the release can materialize
  configs without shelling out to the checkout.
  """
  @spec materialize(map(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def materialize(workspace, opts \\ []) when is_map(workspace) do
    with {:ok, token} <- agent_token(workspace),
         {:ok, staging} <- staging_home(workspace, opts) do
      urls = mcp_urls(workspace, opts)
      checkout = Keyword.get(opts, :checkout) || workspace[:path] || workspace["path"]
      :ok = ensure_staging_dirs(staging)

      :ok = write_grok_config(staging, urls, workspace)
      :ok = write_codex_config(staging, urls, workspace)
      :ok = write_opencode_config(staging, urls, workspace)
      :ok = write_mcp_json(staging, urls, token, workspace)
      :ok = stage_agent_scripts(staging)
      :ok = write_claude_hooks_settings(staging)
      :ok = write_env_sh(staging, workspace, urls, token, checkout, opts)

      maybe_copy_to_checkout(staging, checkout, opts)

      {:ok, staging}
    end
  end

  # sobelow_skip ["Traversal.FileModule"]
  defp ensure_staging_dirs(staging) do
    :ok = File.mkdir_p(Path.join(staging, "grok"))
    :ok = File.mkdir_p(Path.join(staging, "codex"))
    File.mkdir_p(Path.join(staging, "cursor"))
  end

  # The MCP endpoints reject tools/call made with the global admin token
  # (see DevIdeWeb.Endpoint.reject_global_mcp_tool_calls/2), so env.sh must
  # carry the workspace-scoped token.
  defp agent_token(workspace), do: WorkspaceTokens.for_agent(workspace)

  defp non_empty_env(name) do
    case System.get_env(name) do
      value when is_binary(value) and value != "" -> value
      _ -> nil
    end
  end

  defp staging_home(workspace, opts) do
    default_staging =
      Path.join([home_dir(), ".devide", "agent-mcp", workspace_name(workspace)])

    staging =
      Keyword.get(opts, :staging_home) ||
        env_staging_home_if_matching(default_staging) ||
        default_staging

    {:ok, staging}
  rescue
    e in [ArgumentError] -> {:error, e}
  end

  # Mirrors scripts/materialize-agent-mcp.sh: only trust an inherited
  # DEVIDE_AGENT_MCP_HOME if it already points at *this* workspace's staging
  # dir. Otherwise it's a leftover from whichever workspace last exported it
  # into the shared OS process env (e.g. mix test run from an agent pane shell
  # that sourced .devbox-agent.env) and must not clobber a different
  # workspace's config.
  defp env_staging_home_if_matching(default_staging) do
    case non_empty_env("DEVIDE_AGENT_MCP_HOME") do
      ^default_staging = value -> value
      _ -> nil
    end
  end

  defp home_dir do
    System.get_env("HOME") || System.get_env("USERPROFILE") ||
      raise ArgumentError, "HOME or USERPROFILE is required to materialize agent MCP configs"
  end

  defp workspace_name(workspace) do
    Map.get(workspace, :name) || Map.get(workspace, "name") ||
      Map.get(workspace, :id) || Map.get(workspace, "id") ||
      "workspace"
  end

  defp workspace_id(workspace) do
    Map.get(workspace, :id) || Map.get(workspace, "id")
  end

  defp mcp_urls(workspace, opts) do
    id = workspace_id(workspace)
    tidewave = TidewaveMCP.resolve_url(workspace, opts)

    %{
      terminal: MCPUrls.terminal_url(id, opts),
      preview: MCPUrls.preview_url(id, opts),
      artifact: MCPUrls.artifact_url(id),
      tidewave: tidewave,
      tidewave_key: if(tidewave, do: TidewaveMCP.server_key(workspace), else: nil)
    }
  end

  defp write_grok_config(staging, urls, workspace) do
    {terminal_key, preview_key, artifact_key} = server_keys(workspace)

    content = """
    # Generated by DevIDE.Agents.MCPMaterializer — do not edit by hand.
    [mcp_servers.#{terminal_key}]
    url = "#{urls.terminal}"
    enabled = true

    [mcp_servers.#{terminal_key}.headers]
    Authorization = "Bearer ${DEV_IDE_API_TOKEN}"

    [mcp_servers.#{preview_key}]
    url = "#{urls.preview}"
    enabled = true

    [mcp_servers.#{preview_key}.headers]
    Authorization = "Bearer ${DEV_IDE_API_TOKEN}"

    [mcp_servers.#{artifact_key}]
    url = "#{urls.artifact}"
    enabled = true

    [mcp_servers.#{artifact_key}.headers]
    Authorization = "Bearer ${DEV_IDE_API_TOKEN}"
    #{tidewave_grok_block(urls)}
    """

    write_file(Path.join(staging, "grok/config.toml"), content)
  end

  defp write_codex_config(staging, _urls, _workspace) do
    content = """
    # Generated by DevIDE.Agents.MCPMaterializer — do not edit by hand.
    # DevIDE MCP is injected into Codex by scripts/launch-devide-agent.sh with
    # per-launch -c overrides. Keeping this file free of DevIDE MCP entries prevents
    # plain Codex startups from requiring a DevIDE token in the environment.
    """

    write_file(Path.join(staging, "codex/config.toml"), content)
  end

  defp write_opencode_config(staging, urls, workspace) do
    {terminal_key, preview_key, artifact_key} = server_keys(workspace)

    mcp =
      %{
        terminal_key => %{
          "type" => "remote",
          "url" => urls.terminal,
          "enabled" => true,
          "oauth" => false,
          "headers" => %{"Authorization" => "Bearer {env:DEV_IDE_API_TOKEN}"}
        },
        preview_key => %{
          "type" => "remote",
          "url" => urls.preview,
          "enabled" => true,
          "oauth" => false,
          "headers" => %{"Authorization" => "Bearer {env:DEV_IDE_API_TOKEN}"}
        },
        artifact_key => %{
          "type" => "remote",
          "url" => urls.artifact,
          "enabled" => true,
          "oauth" => false,
          "headers" => %{"Authorization" => "Bearer {env:DEV_IDE_API_TOKEN}"}
        }
      }
      |> Map.merge(tidewave_opencode_entries(urls))

    payload = %{
      "$schema" => "https://opencode.ai/config.json",
      "mcp" => mcp
    }

    write_file(Path.join(staging, "opencode.json"), Jason.encode!(payload, pretty: true) <> "\n")
  end

  defp write_mcp_json(staging, urls, _token, workspace) do
    {terminal_key, preview_key, artifact_key} = server_keys(workspace)
    bearer = "Bearer ${DEV_IDE_API_TOKEN}"

    servers =
      %{
        terminal_key => %{
          "type" => "http",
          "url" => urls.terminal,
          "headers" => %{"Authorization" => bearer}
        },
        preview_key => %{
          "type" => "http",
          "url" => urls.preview,
          "headers" => %{"Authorization" => bearer}
        },
        artifact_key => %{
          "type" => "http",
          "url" => urls.artifact,
          "headers" => %{"Authorization" => bearer}
        }
      }
      |> Map.merge(tidewave_mcp_json_entries(urls))

    payload = %{"mcpServers" => servers}

    json = Jason.encode!(payload, pretty: true) <> "\n"
    :ok = write_file(Path.join(staging, ".mcp.json"), json)
    write_file(Path.join(staging, "cursor/mcp.json"), json)
  end

  # Copy the checkout-independent agent hook scripts into the workspace staging
  # home so DevIDE's hooks resolve regardless of which project is the checkout.
  # $DEVIDE_SCRIPTS previously pointed at "<checkout>/scripts", which only exists
  # when the paired project is the dev_ide repo itself; every other workspace hit
  # "devide-agent-state.sh: not found". Source is the release's priv/scripts (dev
  # falls back to the checkout tree), mirroring scripts/materialize-agent-mcp.sh.
  @staged_agent_scripts ~w(devide-agent-state.sh devide-codex-notify.sh)

  # sobelow_skip ["Traversal.FileModule"]
  defp stage_agent_scripts(staging) do
    Enum.each(@staged_agent_scripts, fn name ->
      case priv_script_source(name) do
        {:ok, src} ->
          dest = Path.join(staging, name)
          :ok = File.cp(src, dest)
          File.chmod(dest, 0o755)

        :error ->
          :ok
      end
    end)

    :ok
  end

  defp priv_script_source(name) do
    rel = Path.join(["priv", "scripts", name])

    release_path =
      if Code.ensure_loaded?(Application),
        do: Application.app_dir(:dev_ide, rel),
        else: rel

    source_path = Path.expand(rel)

    cond do
      File.regular?(release_path) -> {:ok, release_path}
      File.regular?(source_path) -> {:ok, source_path}
      true -> :error
    end
  end

  # Claude Code hooks settings, injected by the launcher via `claude --settings`.
  # The hook command runs through a shell, so $DEVIDE_AGENT_MCP_HOME (the staging
  # home, exported by env.sh) resolves at hook time and holds the staged copy.
  # Mirrors scripts/materialize-agent-mcp.sh.
  # staging is the workspace MCP staging directory; the written filename is fixed.
  # sobelow_skip ["Traversal.FileModule"]
  defp write_claude_hooks_settings(staging) do
    command = ~s("$DEVIDE_AGENT_MCP_HOME"/devide-agent-state.sh)
    entry = [%{"hooks" => [%{"type" => "command", "command" => command, "timeout" => 5}]}]

    pretooluse = [
      %{
        "matcher" => "*",
        "hooks" => [%{"type" => "command", "command" => command, "timeout" => 5}]
      }
    ]

    settings = %{
      "hooks" => %{
        "UserPromptSubmit" => entry,
        "PreToolUse" => pretooluse,
        "Notification" => entry,
        "Stop" => entry,
        "SessionStart" => entry,
        "SessionEnd" => entry
      }
    }

    path = Path.join(staging, "claude-hooks-settings.json")
    :ok = write_file(path, Jason.encode!(settings, pretty: true) <> "\n")
    File.chmod(path, 0o600)
    write_claude_sidechat_settings(staging, command)
    :ok
  end

  # Read-only advisor launch (--sidechat): same hooks, deny Edit/Write/Bash.
  # sobelow_skip ["Traversal.FileModule"]
  defp write_claude_sidechat_settings(staging, command) do
    entry = [%{"hooks" => [%{"type" => "command", "command" => command, "timeout" => 5}]}]

    pretooluse = [
      %{
        "matcher" => "*",
        "hooks" => [%{"type" => "command", "command" => command, "timeout" => 5}]
      }
    ]

    settings = %{
      "hooks" => %{
        "UserPromptSubmit" => entry,
        "PreToolUse" => pretooluse,
        "Notification" => entry,
        "Stop" => entry,
        "SessionStart" => entry,
        "SessionEnd" => entry
      },
      "permissions" => %{
        "deny" => ["Edit", "Write", "Bash"]
      }
    }

    path = Path.join(staging, "claude-sidechat-settings.json")
    :ok = write_file(path, Jason.encode!(settings, pretty: true) <> "\n")
    File.chmod(path, 0o600)
    :ok
  end

  defp server_keys(workspace) do
    slug =
      workspace
      |> workspace_name()
      |> String.replace(~r/[^a-zA-Z0-9]+/, "-")
      |> String.trim("-")
      |> String.downcase()

    slug = if slug == "", do: "workspace", else: slug
    {"devide-terminal-#{slug}", "devide-preview-#{slug}", "devide-artifact-#{slug}"}
  end

  # sobelow_skip ["Traversal.FileModule"]
  defp write_env_sh(staging, workspace, urls, token, checkout, opts) do
    workspace_id = workspace_id(workspace)
    workspace_name = workspace_name(workspace)
    env_sh = Path.join(staging, "env.sh")
    scripts = if checkout != "", do: Path.join(checkout, "scripts"), else: ""

    tmux_session = Keyword.get(opts, :tmux_session)

    content = """
    # Generated by DevIDE.Agents.MCPMaterializer
    export DEV_IDE_API_TOKEN=#{quote_env_sh(sanitize_token(token))}
    export DEVIDE_WORKSPACE_ID=#{quote_env_sh(workspace_id)}
    export DEVIDE_WORKSPACE_NAME=#{quote_env_sh(workspace_name)}
    export DEVIDE_TERMINAL_MCP_URL=#{quote_env_sh(urls.terminal)}
    export DEVIDE_PREVIEW_MCP_URL=#{quote_env_sh(urls.preview)}
    export DEVIDE_ARTIFACT_MCP_URL=#{quote_env_sh(urls.artifact)}
    #{tmux_session_env_export(tmux_session)}
    #{tidewave_env_export(urls)}
    #{auth_profile_env_exports(workspace)}
    export DEVIDE_CHECKOUT=#{quote_env_sh(checkout)}
    export DEVIDE_AGENT_MCP_HOME=#{quote_env_sh(staging)}
    export DEVIDE_SCRIPTS=#{quote_env_sh(scripts)}
    export DEVIDE_AGENT_ENV_FILE=#{quote_env_sh(env_sh)}
    export DEV_IDE_NPM_PREFIX="${DEV_IDE_NPM_PREFIX:-${HOME}/.local/share/npm-global}"
    export PATH="#{AgentShims.bin_dir()}:${DEV_IDE_NPM_PREFIX}/bin:${PATH}"
    """

    write_file(env_sh, content)
    File.chmod(env_sh, 0o600)
    :ok
  end

  defp tmux_session_env_export(session) when is_binary(session) and session != "" do
    "export DEVIDE_TMUX_SESSION=#{quote_env_sh(sanitize_token(session))}"
  end

  defp tmux_session_env_export(_), do: ""

  # sobelow_skip ["Traversal.FileModule"]
  defp maybe_copy_to_checkout(staging, checkout, opts)
       when is_binary(checkout) and checkout != "" do
    if File.dir?(checkout) do
      # Claude reads its workspace-isolated staging `.mcp.json` via
      # `claude --mcp-config` (see scripts/launch-devide-agent.sh); only Cursor
      # needs a file in the checkout. Copying `.mcp.json` here previously made a
      # shared checkout accumulate every workspace's servers, so it is omitted.
      checkout_cursor_dir = Path.join(checkout, ".cursor")
      checkout_cursor_mcp = Path.join(checkout_cursor_dir, "mcp.json")

      :ok = File.mkdir_p(checkout_cursor_dir)
      :ok = File.cp(Path.join(staging, "cursor/mcp.json"), checkout_cursor_mcp)
      File.chmod(checkout_cursor_mcp, 0o600)

      if Keyword.get(opts, :copy_grok_to_checkout, false) do
        merge_mcp_json(Path.join(staging, ".mcp.json"), Path.join(checkout, ".mcp.json"))
      end
    end

    :ok
  end

  defp maybe_copy_to_checkout(_staging, _checkout, _opts), do: :ok

  # Grok discovers MCP servers from the project root. Preserve user-owned
  # servers and replace only the workspace-scoped DevIDE entries generated for
  # this launch. The generated file contains an environment placeholder, never
  # the bearer token itself.
  # sobelow_skip ["Traversal.FileModule"]
  defp merge_mcp_json(generated_path, checkout_path) do
    generated = generated_path |> File.read!() |> Jason.decode!()
    existing = read_json_map(checkout_path)

    merged =
      Map.update(existing, "mcpServers", generated["mcpServers"], fn servers ->
        Map.merge(if(is_map(servers), do: servers, else: %{}), generated["mcpServers"])
      end)

    write_file(checkout_path, Jason.encode!(merged, pretty: true) <> "\n")
    File.chmod(checkout_path, 0o600)
    :ok
  end

  # sobelow_skip ["Traversal.FileModule"]
  defp read_json_map(path) do
    with {:ok, content} <- File.read(path),
         {:ok, value} when is_map(value) <- Jason.decode(content) do
      value
    else
      {:error, :enoent} -> %{}
      {:error, reason} -> raise File.Error, reason: reason, action: "read", path: path
      _ -> raise ArgumentError, "existing #{path} must contain a JSON object"
    end
  end

  # sobelow_skip ["Traversal.FileModule"]
  defp write_file(path, content) do
    path |> Path.dirname() |> File.mkdir_p()
    File.write!(path, content)
    :ok
  end

  defp tidewave_grok_block(%{tidewave: url, tidewave_key: key})
       when is_binary(url) and is_binary(key) do
    """

    [mcp_servers.#{key}]
    url = "#{url}"
    enabled = true
    """
  end

  defp tidewave_grok_block(_), do: ""

  defp tidewave_opencode_entries(%{tidewave: url, tidewave_key: key})
       when is_binary(url) and is_binary(key) do
    %{
      key => %{
        "type" => "remote",
        "url" => url,
        "enabled" => true,
        "oauth" => false
      }
    }
  end

  defp tidewave_opencode_entries(_), do: %{}

  defp tidewave_mcp_json_entries(%{tidewave: url, tidewave_key: key})
       when is_binary(url) and is_binary(key) do
    %{key => %{"type" => "http", "url" => url}}
  end

  defp tidewave_mcp_json_entries(_), do: %{}

  defp tidewave_env_export(%{tidewave: url}) when is_binary(url) do
    "export DEVIDE_TIDEWAVE_MCP_URL=#{quote_env_sh(url)}"
  end

  defp tidewave_env_export(_), do: ""

  defp quote_env_sh(value) when is_binary(value) do
    "'" <> String.replace(value, "'", "'\\''") <> "'"
  end

  defp auth_profile_env_exports(workspace) do
    workspace
    |> AuthProfile.env_for_workspace()
    |> Enum.map_join("\n", fn {key, value} ->
      "export #{key}=#{quote_env_sh(sanitize_token(value))}"
    end)
  end

  defp sanitize_token(token) when is_binary(token) do
    token = String.trim(token)

    case token do
      <<q, rest::binary>> when q in [?\', ?\"] ->
        size = byte_size(rest)

        if size > 0 and :binary.last(rest) == q do
          :binary.part(rest, 0, size - 1)
        else
          token
        end

      _ ->
        token
    end
  end
end
