defmodule Casein.Agents.MCPMaterializer do
  @moduledoc """
  Writes per-workspace MCP client config files (Grok, Codex, opencode, Cursor,
  `.mcp.json`, `env.sh`) into a staging home so external agents connect to the
  Casein MCP endpoints with the right bearer token. Generic runtime configs may
  include Tidewave; the managed Grok bundle deliberately contains only Casein's
  authenticated terminal, preview, and artifact surfaces.
  """

  alias Casein.Agents.{
    AgentShims,
    AuthProfile,
    GrokCapabilityBundle,
    MCPUrls,
    TidewaveMCP,
    WorkspaceTokens
  }

  alias Casein.Workspaces

  @doc """
  Write per-workspace MCP client configs for external agents.

  Mirrors `scripts/materialize-agent-mcp.sh` so the release can materialize
  configs without shelling out to the checkout.
  """
  @spec materialize(map(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def materialize(workspace, opts \\ []) when is_map(workspace) do
    with {:ok, token} <- agent_token(workspace),
         {:ok, staging} <- staging_home(workspace, opts) do
      urls = mcp_urls(workspace, opts)
      checkout = Keyword.get(opts, :checkout) || workspace[:path] || workspace["path"] || ""
      :ok = ensure_staging_dirs(staging)

      :ok = write_grok_config(staging, urls, workspace)
      :ok = write_codex_config(staging, urls, workspace)
      :ok = write_opencode_config(staging, urls, workspace)
      :ok = write_mcp_json(staging, urls, token, workspace)
      :ok = write_grok_mcp_json(staging, urls, workspace)
      :ok = stage_agent_scripts(staging)
      :ok = write_claude_hooks_settings(staging)

      with {:ok, bundle} <- write_grok_bundle(staging, opts),
           {:ok, leader_socket} <-
             GrokCapabilityBundle.leader_socket(to_string(workspace_id(workspace)), checkout) do
        :ok = write_env_sh(staging, workspace, urls, token, checkout, bundle, leader_socket, opts)
        maybe_copy_to_checkout(staging, checkout, opts)
        {:ok, staging}
      end
    end
  end

  # sobelow_skip ["Traversal.FileModule"]
  defp ensure_staging_dirs(staging) do
    :ok = File.mkdir_p(Path.join(staging, "grok"))
    :ok = File.mkdir_p(Path.join(staging, "codex"))
    File.mkdir_p(Path.join(staging, "cursor"))
  end

  # The MCP endpoints reject tools/call made with the global admin token
  # (see CaseinWeb.Endpoint.reject_global_mcp_tool_calls/2), so env.sh must
  # carry the workspace-scoped token.
  defp agent_token(workspace), do: WorkspaceTokens.for_agent(workspace)

  defp non_empty_env(name) do
    case System.get_env(name) do
      value when is_binary(value) and value != "" -> value
      _ -> nil
    end
  end

  defp staging_home(workspace, opts) do
    default_staging =
      Path.join([home_dir(), ".casein", "agent-mcp", workspace_name(workspace)])

    staging =
      Keyword.get(opts, :staging_home) ||
        env_staging_home_if_matching(default_staging) ||
        default_staging

    {:ok, staging}
  rescue
    e in [ArgumentError] -> {:error, e}
  end

  # Mirrors scripts/materialize-agent-mcp.sh: only trust an inherited
  # DEVIDE_AGENT_MCP_HOME if it already points at *this* workspace's staging
  # dir. Otherwise it's a leftover from whichever workspace last exported it
  # into the shared OS process env (e.g. mix test run from an agent pane shell
  # that sourced .devbox-agent.env) and must not clobber a different
  # workspace's config.
  defp env_staging_home_if_matching(default_staging) do
    case non_empty_env("DEVIDE_AGENT_MCP_HOME") do
      ^default_staging = value -> value
      _ -> nil
    end
  end

  defp home_dir do
    # Tests may set `:agent_home_dir` to a writable tmp path when the host
    # `~/.casein/agent-mcp` tree is locked (mode 000 / RO). Production leaves
    # this unset and uses $HOME.
    Application.get_env(:casein, :agent_home_dir) ||
      System.get_env("HOME") ||
      System.get_env("USERPROFILE") ||
      raise ArgumentError, "HOME or USERPROFILE is required to materialize agent MCP configs"
  end

  defp workspace_name(workspace) do
    Map.get(workspace, :name) || Map.get(workspace, "name") ||
      Map.get(workspace, :id) || Map.get(workspace, "id") ||
      "workspace"
  end

  defp workspace_id(workspace) do
    Map.get(workspace, :id) || Map.get(workspace, "id")
  end

  defp mcp_urls(workspace, opts) do
    id = workspace_id(workspace)
    tidewave = TidewaveMCP.resolve_url(workspace, opts)

    %{
      terminal: MCPUrls.terminal_url(id, opts),
      preview: MCPUrls.preview_url(id, opts),
      artifact: MCPUrls.artifact_url(id),
      tidewave: tidewave,
      tidewave_key: if(tidewave, do: TidewaveMCP.server_key(workspace), else: nil)
    }
  end

  defp write_grok_config(staging, urls, workspace) do
    {terminal_key, preview_key, artifact_key} = server_keys(workspace)

    content = """
    # Generated by Casein.Agents.MCPMaterializer — do not edit by hand.
    [mcp_servers.#{terminal_key}]
    url = "#{urls.terminal}"
    enabled = true

    [mcp_servers.#{terminal_key}.headers]
    Authorization = "Bearer ${CASEIN_API_TOKEN}"
    X-Casein-Caller-Pane = "${DEVIDE_CALLER_PANE}"

    [mcp_servers.#{preview_key}]
    url = "#{urls.preview}"
    enabled = true

    [mcp_servers.#{preview_key}.headers]
    Authorization = "Bearer ${CASEIN_API_TOKEN}"

    [mcp_servers.#{artifact_key}]
    url = "#{urls.artifact}"
    enabled = true

    [mcp_servers.#{artifact_key}.headers]
    Authorization = "Bearer ${CASEIN_API_TOKEN}"
    #{tidewave_grok_block(urls)}
    """

    write_file(Path.join(staging, "grok/config.toml"), content)
  end

  defp write_codex_config(staging, _urls, _workspace) do
    content = """
    # Generated by Casein.Agents.MCPMaterializer — do not edit by hand.
    # Casein MCP is injected into Codex by scripts/launch-casein-agent.sh with
    # per-launch -c overrides. Keeping this file free of Casein MCP entries prevents
    # plain Codex startups from requiring a Casein token in the environment.
    """

    write_file(Path.join(staging, "codex/config.toml"), content)
  end

  defp write_opencode_config(staging, urls, workspace) do
    {terminal_key, preview_key, artifact_key} = server_keys(workspace)

    mcp =
      %{
        terminal_key => %{
          "type" => "remote",
          "url" => urls.terminal,
          "enabled" => true,
          "oauth" => false,
          "headers" => %{
            "Authorization" => "Bearer {env:CASEIN_API_TOKEN}",
            "X-Casein-Caller-Pane" => "{env:DEVIDE_CALLER_PANE}"
          }
        },
        preview_key => %{
          "type" => "remote",
          "url" => urls.preview,
          "enabled" => true,
          "oauth" => false,
          "headers" => %{"Authorization" => "Bearer {env:CASEIN_API_TOKEN}"}
        },
        artifact_key => %{
          "type" => "remote",
          "url" => urls.artifact,
          "enabled" => true,
          "oauth" => false,
          "headers" => %{"Authorization" => "Bearer {env:CASEIN_API_TOKEN}"}
        }
      }
      |> Map.merge(tidewave_opencode_entries(urls))

    payload = %{
      "$schema" => "https://opencode.ai/config.json",
      "mcp" => mcp
    }

    write_file(Path.join(staging, "opencode.json"), Jason.encode!(payload, pretty: true) <> "\n")
  end

  defp write_mcp_json(staging, urls, _token, workspace) do
    {terminal_key, preview_key, artifact_key} = server_keys(workspace)
    bearer = "Bearer ${CASEIN_API_TOKEN}"

    servers =
      %{
        terminal_key => %{
          "type" => "http",
          "url" => urls.terminal,
          "headers" => %{
            "Authorization" => bearer,
            # Anchors terminal MCP pane resolution to the calling agent's own
            # pane; expanded per process from launch-casein-agent.sh's export.
            # The server ignores empty/unexpanded values.
            "X-Casein-Caller-Pane" => "${DEVIDE_CALLER_PANE}"
          }
        },
        preview_key => %{
          "type" => "http",
          "url" => urls.preview,
          "headers" => %{"Authorization" => bearer}
        },
        artifact_key => %{
          "type" => "http",
          "url" => urls.artifact,
          "headers" => %{"Authorization" => bearer}
        }
      }
      |> Map.merge(tidewave_mcp_json_entries(urls))

    payload = %{"mcpServers" => servers}

    json = Jason.encode!(payload, pretty: true) <> "\n"
    :ok = write_file(Path.join(staging, ".mcp.json"), json)
    write_file(Path.join(staging, "cursor/mcp.json"), json)
  end

  # Managed Grok is authorized by a Casein capability bearer. Tidewave is an
  # external dev endpoint outside ApiAuth, so including it would bypass the
  # exact capability tool grant.
  defp write_grok_mcp_json(staging, urls, workspace) do
    {terminal_key, preview_key, artifact_key} = server_keys(workspace)
    bearer = "Bearer ${CASEIN_API_TOKEN}"

    payload = %{
      "mcpServers" => %{
        terminal_key => %{
          "type" => "http",
          "url" => urls.terminal,
          "headers" => %{"Authorization" => bearer}
        },
        preview_key => %{
          "type" => "http",
          "url" => urls.preview,
          "headers" => %{"Authorization" => bearer}
        },
        artifact_key => %{
          "type" => "http",
          "url" => urls.artifact,
          "headers" => %{"Authorization" => bearer}
        }
      }
    }

    write_file(Path.join(staging, "grok/.mcp.json"), Jason.encode!(payload, pretty: true) <> "\n")
  end

  # Copy the checkout-independent agent hook scripts into the workspace staging
  # home so Casein's hooks resolve regardless of which project is the checkout.
  # $DEVIDE_SCRIPTS previously pointed at "<checkout>/scripts", which only exists
  # when the paired project is the dev_ide repo itself; every other workspace hit
  # "casein-agent-state.sh: not found". Source is the release's priv/scripts (dev
  # falls back to the checkout tree), mirroring scripts/materialize-agent-mcp.sh.
  @staged_agent_scripts ~w(casein-agent-state.sh casein-codex-notify.sh)

  # sobelow_skip ["Traversal.FileModule"]
  defp stage_agent_scripts(staging) do
    Enum.each(@staged_agent_scripts, fn name ->
      case priv_script_source(name) do
        {:ok, src} ->
          dest = Path.join(staging, name)
          :ok = File.cp(src, dest)
          File.chmod(dest, 0o755)

        :error ->
          :ok
      end
    end)

    :ok
  end

  defp priv_script_source(name) do
    rel = Path.join(["priv", "scripts", name])

    release_path =
      if Code.ensure_loaded?(Application),
        do: Application.app_dir(:casein, rel),
        else: rel

    source_path = Path.expand(rel)

    cond do
      File.regular?(release_path) -> {:ok, release_path}
      File.regular?(source_path) -> {:ok, source_path}
      true -> :error
    end
  end

  # Claude Code hooks settings, injected by the launcher via `claude --settings`.
  # The hook command runs through a shell, so $DEVIDE_AGENT_MCP_HOME (the staging
  # home, exported by env.sh) resolves at hook time and holds the staged copy.
  # Mirrors scripts/materialize-agent-mcp.sh.
  # staging is the workspace MCP staging directory; the written filename is fixed.
  # sobelow_skip ["Traversal.FileModule"]
  defp write_claude_hooks_settings(staging) do
    command = ~s("$DEVIDE_AGENT_MCP_HOME"/casein-agent-state.sh)
    entry = [%{"hooks" => [%{"type" => "command", "command" => command, "timeout" => 5}]}]

    pretooluse = [
      %{
        "matcher" => "*",
        "hooks" => [%{"type" => "command", "command" => command, "timeout" => 5}]
      }
    ]

    settings = %{
      "hooks" => %{
        "UserPromptSubmit" => entry,
        "PreToolUse" => pretooluse,
        "Notification" => entry,
        "Stop" => entry,
        "SessionStart" => entry,
        "SessionEnd" => entry
      }
    }

    path = Path.join(staging, "claude-hooks-settings.json")
    :ok = write_file(path, Jason.encode!(settings, pretty: true) <> "\n")
    File.chmod(path, 0o600)
    write_claude_sidechat_settings(staging, command)
    :ok
  end

  # Read-only advisor launch (--sidechat): same hooks, deny Edit/Write/Bash.
  # sobelow_skip ["Traversal.FileModule"]
  defp write_claude_sidechat_settings(staging, command) do
    entry = [%{"hooks" => [%{"type" => "command", "command" => command, "timeout" => 5}]}]

    pretooluse = [
      %{
        "matcher" => "*",
        "hooks" => [%{"type" => "command", "command" => command, "timeout" => 5}]
      }
    ]

    settings = %{
      "hooks" => %{
        "UserPromptSubmit" => entry,
        "PreToolUse" => pretooluse,
        "Notification" => entry,
        "Stop" => entry,
        "SessionStart" => entry,
        "SessionEnd" => entry
      },
      "permissions" => %{
        "deny" => ["Edit", "Write", "Bash"]
      }
    }

    path = Path.join(staging, "claude-sidechat-settings.json")
    :ok = write_file(path, Jason.encode!(settings, pretty: true) <> "\n")
    File.chmod(path, 0o600)
    :ok
  end

  defp write_grok_bundle(staging, opts) do
    hook_config = Path.join(staging, "grok-bundle-hooks.json")
    :ok = write_file(hook_config, Jason.encode!(grok_bundle_hooks(), pretty: true) <> "\n")

    skills_root = Keyword.get(opts, :grok_skills_root, Path.expand(".claude/skills"))

    skills =
      ~w(preview-ui-walk verify workspace-agent-pair)
      |> Enum.filter(&File.dir?(Path.join(skills_root, &1)))

    GrokCapabilityBundle.compile(
      bundle_root: Keyword.get(opts, :grok_bundle_root, GrokCapabilityBundle.root()),
      mcp_config: Path.join(staging, "grok/.mcp.json"),
      hook_config: hook_config,
      hook_script: Path.join(staging, "casein-agent-state.sh"),
      hooks: Keyword.get(opts, :agent_state_hooks, true),
      skills_root: skills_root,
      skills: skills
    )
  end

  defp grok_bundle_hooks do
    command =
      ~s(sh -c 'if [ -n "${GROK_PLUGIN_ROOT:-}" ] && [ -x "${GROK_PLUGIN_ROOT}/hooks/casein-agent-state.sh" ]; then exec env -u XAI_API_KEY -u GROK_CODE_XAI_API_KEY -u GROK_AUTH -u GROK_AUTH_PATH -u GROK_AUTH_PROVIDER_COMMAND "${GROK_PLUGIN_ROOT}/hooks/casein-agent-state.sh"; fi; [ -n "${DEVIDE_AGENT_MCP_HOME:-}" ] || exit 0; exec env -u XAI_API_KEY -u GROK_CODE_XAI_API_KEY -u GROK_AUTH -u GROK_AUTH_PATH -u GROK_AUTH_PROVIDER_COMMAND "${DEVIDE_AGENT_MCP_HOME}/casein-agent-state.sh"')

    entry = [%{"hooks" => [%{"type" => "command", "command" => command, "timeout" => 5}]}]

    %{
      "hooks" =>
        Map.new(
          ~w(SessionStart UserPromptSubmit PreToolUse Notification Stop StopFailure SessionEnd),
          &{&1, entry}
        )
    }
  end

  defp server_keys(workspace) do
    slug =
      workspace
      |> workspace_name()
      |> String.replace(~r/[^a-zA-Z0-9]+/, "-")
      |> String.trim("-")
      |> String.downcase()

    slug = if slug == "", do: "workspace", else: slug
    {"casein-terminal-#{slug}", "casein-preview-#{slug}", "casein-artifact-#{slug}"}
  end

  # sobelow_skip ["Traversal.FileModule"]
  defp write_env_sh(staging, workspace, urls, token, checkout, bundle, leader_socket, opts) do
    workspace_id = workspace_id(workspace)
    workspace_name = workspace_name(workspace)
    env_sh = Path.join(staging, "env.sh")
    scripts = if checkout != "", do: Path.join(checkout, "scripts"), else: ""

    tmux_session = Keyword.get(opts, :tmux_session)

    content = """
    # Generated by Casein.Agents.MCPMaterializer
    export CASEIN_API_TOKEN=#{quote_env_sh(sanitize_token(token))}
    export DEVIDE_WORKSPACE_ID=#{quote_env_sh(workspace_id)}
    export DEVIDE_WORKSPACE_NAME=#{quote_env_sh(workspace_name)}
    export DEVIDE_WORKSPACE_MODE=#{quote_env_sh(workspace_mode(workspace))}
    export DEVIDE_API_BASE_URL=#{quote_env_sh(api_base_url(urls.terminal))}
    export DEVIDE_CODEX_HOOK_URL=#{quote_env_sh(codex_hook_url(urls.terminal, workspace_id))}
    export DEVIDE_TERMINAL_MCP_URL=#{quote_env_sh(urls.terminal)}
    export DEVIDE_PREVIEW_MCP_URL=#{quote_env_sh(urls.preview)}
    export DEVIDE_ARTIFACT_MCP_URL=#{quote_env_sh(urls.artifact)}
    #{tmux_session_env_export(tmux_session)}
    #{tidewave_env_export(urls)}
    #{auth_profile_env_exports(workspace)}
    export DEVIDE_CHECKOUT=#{quote_env_sh(checkout)}
    export DEVIDE_AGENT_MCP_HOME=#{quote_env_sh(staging)}
    export DEVIDE_GROK_BUNDLE_DIR=#{quote_env_sh(bundle.dir)}
    export DEVIDE_GROK_BUNDLE_DIGEST=#{quote_env_sh(bundle.digest)}
    export DEVIDE_GROK_LEADER_ROOT=#{quote_env_sh(Path.dirname(leader_socket))}
    export DEVIDE_GROK_LEADER_SOCKET=#{quote_env_sh(leader_socket)}
    export DEVIDE_SCRIPTS=#{quote_env_sh(scripts)}
    export DEVIDE_AGENT_ENV_FILE=#{quote_env_sh(env_sh)}
    export CASEIN_NPM_PREFIX="${CASEIN_NPM_PREFIX:-${HOME}/.local/share/npm-global}"
    export PATH="#{AgentShims.bin_dir()}:${CASEIN_NPM_PREFIX}/bin:${PATH}"
    """

    write_file(env_sh, content)
    File.chmod(env_sh, 0o600)
    :ok
  end

  defp tmux_session_env_export(session) when is_binary(session) and session != "" do
    "export DEVIDE_TMUX_SESSION=#{quote_env_sh(sanitize_token(session))}"
  end

  defp tmux_session_env_export(_), do: ""

  # sobelow_skip ["Traversal.FileModule"]
  defp maybe_copy_to_checkout(staging, checkout, _opts)
       when is_binary(checkout) and checkout != "" do
    if File.dir?(checkout) do
      # Claude reads its workspace-isolated staging `.mcp.json` via
      # `claude --mcp-config` (see scripts/launch-casein-agent.sh); only Cursor
      # needs a file in the checkout. Copying `.mcp.json` here previously made a
      # shared checkout accumulate every workspace's servers, so it is omitted.
      checkout_cursor_dir = Path.join(checkout, ".cursor")
      checkout_cursor_mcp = Path.join(checkout_cursor_dir, "mcp.json")

      :ok = File.mkdir_p(checkout_cursor_dir)
      :ok = File.cp(Path.join(staging, "cursor/mcp.json"), checkout_cursor_mcp)
      File.chmod(checkout_cursor_mcp, 0o600)
    end

    :ok
  end

  defp maybe_copy_to_checkout(_staging, _checkout, _opts), do: :ok

  # sobelow_skip ["Traversal.FileModule"]
  defp write_file(path, content) do
    path |> Path.dirname() |> File.mkdir_p()
    File.write!(path, content)
    :ok
  end

  defp tidewave_grok_block(%{tidewave: url, tidewave_key: key})
       when is_binary(url) and is_binary(key) do
    """

    [mcp_servers.#{key}]
    url = "#{url}"
    enabled = true
    """
  end

  defp tidewave_grok_block(_), do: ""

  defp tidewave_opencode_entries(%{tidewave: url, tidewave_key: key})
       when is_binary(url) and is_binary(key) do
    %{
      key => %{
        "type" => "remote",
        "url" => url,
        "enabled" => true,
        "oauth" => false
      }
    }
  end

  defp tidewave_opencode_entries(_), do: %{}

  defp tidewave_mcp_json_entries(%{tidewave: url, tidewave_key: key})
       when is_binary(url) and is_binary(key) do
    %{key => %{"type" => "http", "url" => url}}
  end

  defp tidewave_mcp_json_entries(_), do: %{}

  defp tidewave_env_export(%{tidewave: url}) when is_binary(url) do
    "export DEVIDE_TIDEWAVE_MCP_URL=#{quote_env_sh(url)}"
  end

  defp tidewave_env_export(_), do: ""

  defp workspace_mode(workspace) do
    workspace_id = workspace_id(workspace)

    case Workspaces.mode_for(workspace_id) do
      {mode, _source} -> to_string(mode)
      _other -> workspace |> Map.get(:mode, Map.get(workspace, "mode", :manual)) |> to_string()
    end
  rescue
    _error -> workspace |> Map.get(:mode, Map.get(workspace, "mode", :manual)) |> to_string()
  end

  defp api_base_url(terminal_url) do
    uri = URI.parse(terminal_url)
    URI.to_string(%{uri | path: nil, query: nil, fragment: nil}) |> String.trim_trailing("/")
  end

  defp codex_hook_url(terminal_url, workspace_id) do
    api_base_url(terminal_url) <> "/api/workspaces/#{URI.encode(workspace_id)}/codex/hooks"
  end

  defp quote_env_sh(value) when is_binary(value) do
    "'" <> String.replace(value, "'", "'\\''") <> "'"
  end

  defp auth_profile_env_exports(workspace) do
    workspace
    |> AuthProfile.env_for_workspace()
    |> Enum.map_join("\n", fn {key, value} ->
      "export #{key}=#{quote_env_sh(sanitize_token(value))}"
    end)
  end

  defp sanitize_token(token) when is_binary(token) do
    token = String.trim(token)

    case token do
      <<q, rest::binary>> when q in [?\', ?\"] ->
        size = byte_size(rest)

        if size > 0 and :binary.last(rest) == q do
          :binary.part(rest, 0, size - 1)
        else
          token
        end

      _ ->
        token
    end
  end
end
