// AppDelegate.m — Boots the Mob BEAM on a background thread and presents
// a SwiftUI root view through the iOS scene lifecycle.

#import <UIKit/UIKit.h>
#import <UserNotifications/UserNotifications.h>
#import <pthread.h>
#include <string.h>
#include "erl_nif.h"
#include "mob_beam.h"
#import "MobApp-Swift.h"  // generated by swiftc; exposes MobUIFactory

#define MOB_NOTIFICATION_JSON_MAX_BYTES (64 * 1024)

// Declared in mob_nif — delivers {:push_token, :ios, token} to the registered screen process.
extern void mob_send_push_token(const char* hex_token);
// These direct-delivery callbacks are available in newer Mob runtimes, but
// Mob 0.7.x only exposes the launch-notification store. Weak host definitions
// keep this app link-compatible; a runtime's strong definitions override them.
__attribute__((weak)) void mob_send_push_token_error(const char* reason) {
    (void)reason;
}

__attribute__((weak)) void mob_deliver_notification_json(const char* json) {
    if (!json) {
        return;
    }

    size_t jsonLength = strnlen(json, MOB_NOTIFICATION_JSON_MAX_BYTES + 1);
    if (jsonLength > MOB_NOTIFICATION_JSON_MAX_BYTES) {
        return;
    }

    id<UNUserNotificationCenterDelegate> delegate =
        [UNUserNotificationCenter currentNotificationCenter].delegate;
    Class mobNotificationDelegate = NSClassFromString(@"MobNotificationDelegate");

    if (mobNotificationDelegate && [delegate isKindOfClass:mobNotificationDelegate]) {
        ErlNifEnv* env = enif_alloc_env();
        if (env) {
            ErlNifPid screenPid;
            ERL_NIF_TERM screenName = enif_make_atom(env, "mob_screen");

            if (enif_whereis_pid(env, screenName, &screenPid)) {
                ErlNifBinary payload;
                if (enif_alloc_binary(jsonLength, &payload)) {
                    memcpy(payload.data, json, jsonLength);
                    ERL_NIF_TERM message =
                        enif_make_tuple2(env,
                                         enif_make_atom(env, "mob_launch_notification"),
                                         enif_make_binary(env, &payload));

                    if (enif_send(NULL, &screenPid, env, message)) {
                        enif_free_env(env);
                        return;
                    }
                }
            }

            enif_free_env(env);
        }
    }

    mob_set_launch_notification_json(json);
}

// Code-generated by MobDev.Plugin.IOSBootstrap at build time — registers each
// activated plugin's SwiftUI view with MobNativeViewRegistry.shared. Defined
// via Swift's @_cdecl in the generated file so it's a plain C symbol; safe to
// call before mob_init_ui() even when no plugins are activated (the function
// body is just empty in that case).
extern void mob_register_plugins(void);

static NSString* MobStringValue(id value);
static NSMutableDictionary* MobStringMapFromDictionary(NSDictionary* dict);
static NSString* MobNotificationJSONFromUserInfo(NSDictionary* userInfo);
static NSString* MobNotificationJSONFromReviewURL(NSURL* url);
static void MobStoreLaunchNotificationUserInfo(NSDictionary* userInfo);
static BOOL MobStoreDeepLinkURL(NSURL* url);

static void* beam_thread(void* arg) {
    mob_start_beam((const char*)arg);
    return NULL;
}

static NSString* MobStringValue(id value) {
    if ([value isKindOfClass:[NSString class]]) {
        return value;
    }

    if ([value respondsToSelector:@selector(stringValue)]) {
        return [value stringValue];
    }

    return nil;
}

static NSMutableDictionary* MobStringMapFromDictionary(NSDictionary* dict) {
    NSMutableDictionary* out = [NSMutableDictionary dictionary];

    for (id key in dict) {
        if (![key isKindOfClass:[NSString class]]) {
            continue;
        }

        id value = dict[key];

        if ([value isKindOfClass:[NSDictionary class]]) {
            NSDictionary* nested = MobStringMapFromDictionary(value);
            if (nested.count > 0) {
                out[key] = nested;
            }
        } else if ([value isKindOfClass:[NSArray class]]) {
            out[key] = value;
        } else {
            NSString* stringValue = MobStringValue(value);
            if (stringValue) {
                out[key] = stringValue;
            }
        }
    }

    return out;
}

static NSString* MobNotificationJSONFromUserInfo(NSDictionary* userInfo) {
    NSDictionary* aps = [userInfo[@"aps"] isKindOfClass:[NSDictionary class]] ? userInfo[@"aps"] : @{};
    id alert = aps[@"alert"];
    NSString* title = nil;
    NSString* body = nil;

    if ([alert isKindOfClass:[NSDictionary class]]) {
        title = MobStringValue(alert[@"title"]);
        body = MobStringValue(alert[@"body"]);
    } else {
        body = MobStringValue(alert);
    }

    NSMutableDictionary* data = MobStringMapFromDictionary(userInfo);
    [data removeObjectForKey:@"aps"];

    NSString* notificationID =
        MobStringValue(userInfo[@"id"]) ?:
        MobStringValue(userInfo[@"card_id"]) ?:
        [NSString stringWithFormat:@"push-%@", @((long long)([[NSDate date] timeIntervalSince1970] * 1000))];

    NSMutableDictionary* payload = [@{
        @"id": notificationID,
        @"title": title ?: @"Session alert",
        @"body": body ?: @"Tap to open the session.",
        @"source": @"push",
        @"data": data
    } mutableCopy];

    NSData* jsonData = [NSJSONSerialization dataWithJSONObject:payload options:0 error:nil];
    if (!jsonData) {
        return nil;
    }

    return [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];
}

static NSString* MobNotificationJSONFromReviewURL(NSURL* url) {
    if (![url.scheme isEqualToString:@"devide"] || ![url.host isEqualToString:@"review"]) {
        return nil;
    }

    NSString* path = url.path;
    if (path.length <= 1) {
        return nil;
    }

    NSString* cardID = [[path substringFromIndex:1] stringByRemovingPercentEncoding];
    if (cardID.length == 0) {
        return nil;
    }

    NSMutableDictionary* data = [@{
        @"card_type": @"needs_review",
        @"card_id": cardID,
        @"deep_link": url.absoluteString
    } mutableCopy];

    NSSet* allowedLocatorKeys = [NSSet setWithArray:@[
        @"origin_id", @"workspace_id", @"session_id", @"task_type", @"task_id",
        @"tmux_session", @"window", @"pane", @"tab", @"artifact"
    ]];

    NSURLComponents* components = [NSURLComponents componentsWithURL:url resolvingAgainstBaseURL:NO];
    for (NSURLQueryItem* item in components.queryItems ?: @[]) {
        if ([allowedLocatorKeys containsObject:item.name] && item.value.length > 0) {
            data[item.name] = item.value;
        }
    }

    NSMutableDictionary* payload = [@{
        @"id": [NSString stringWithFormat:@"deep-link-%@", cardID],
        @"title": @"Review requested",
        @"body": @"Review required before work continues",
        @"source": @"deep_link",
        @"data": data
    } mutableCopy];

    NSData* jsonData = [NSJSONSerialization dataWithJSONObject:payload options:0 error:nil];
    if (!jsonData) {
        return nil;
    }

    return [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];
}

static NSString* MobNotificationJSONFromPairURL(NSURL* url) {
    if (![url.scheme isEqualToString:@"devide"] || ![url.host isEqualToString:@"pair"]) {
        return nil;
    }

    NSString* code = nil;
    if (url.path.length > 1) {
        code = [[url.path substringFromIndex:1] stringByRemovingPercentEncoding];
    }

    if (code.length == 0) {
        NSURLComponents* components = [NSURLComponents componentsWithURL:url
                                                 resolvingAgainstBaseURL:NO];
        for (NSURLQueryItem* item in components.queryItems) {
            if ([item.name isEqualToString:@"code"] && item.value.length > 0) {
                code = item.value;
                break;
            }
        }
    }

    if (code.length == 0) {
        return nil;
    }

    NSDictionary* data = @{
        @"action": @"mobile.pair",
        @"pairing_code": code,
        @"deep_link": url.absoluteString
    };

    NSDictionary* payload = @{
        @"id": @"pairing-deep-link",
        @"title": @"Pair Casein",
        @"source": @"deep_link",
        @"data": data
    };

    NSData* jsonData = [NSJSONSerialization dataWithJSONObject:payload options:0 error:nil];
    if (!jsonData) {
        return nil;
    }

    return [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];
}

static void MobStoreLaunchNotificationUserInfo(NSDictionary* userInfo) {
    if (![userInfo isKindOfClass:[NSDictionary class]]) {
        return;
    }

    NSString* json = MobNotificationJSONFromUserInfo(userInfo);
    if (json.length > 0) {
        mob_deliver_notification_json([json UTF8String]);
    }
}

static BOOL MobStoreDeepLinkURL(NSURL* url) {
    NSString* json = MobNotificationJSONFromReviewURL(url);
    if (json.length == 0) {
        json = MobNotificationJSONFromPairURL(url);
    }

    if (json.length == 0) {
        return NO;
    }

    mob_deliver_notification_json([json UTF8String]);
    return YES;
}

@interface SceneDelegate : UIResponder <UIWindowSceneDelegate>
@property (strong, nonatomic) UIWindow *window;
@end

@implementation SceneDelegate

- (void)fitWindowToScene:(UIWindowScene*)windowScene {
    if (!windowScene || !self.window) {
        return;
    }

    // iPadOS can resize a scene without recreating its UIWindow (rotation,
    // split view, Stage Manager / Windowed Apps, keyboard-driven window
    // changes). Keep the hosting controller attached to the authoritative
    // scene coordinate space rather than the size from first connection.
    self.window.frame = windowScene.coordinateSpace.bounds;
    self.window.rootViewController.view.frame = self.window.bounds;
    [self.window.rootViewController.view setNeedsLayout];
    [self.window.rootViewController.view layoutIfNeeded];
}

- (void)scene:(UIScene*)scene
    willConnectToSession:(UISceneSession*)session
    options:(UISceneConnectionOptions*)connectionOptions {
    (void)session;

    if (![scene isKindOfClass:[UIWindowScene class]]) {
        return;
    }

    UIWindow* window = [[UIWindow alloc] initWithWindowScene:(UIWindowScene*)scene];
    UIViewController* vc = [MobUIFactory makeRootViewController];
    window.rootViewController = vc;
    self.window = window;
    [self fitWindowToScene:(UIWindowScene*)scene];
    [window makeKeyAndVisible];

    UNNotificationResponse* response = connectionOptions.notificationResponse;
    NSDictionary* userInfo = response.notification.request.content.userInfo;
    MobStoreLaunchNotificationUserInfo(userInfo);

    for (UIOpenURLContext* context in connectionOptions.URLContexts) {
        MobStoreDeepLinkURL(context.URL);
    }
}

- (void)windowScene:(UIWindowScene*)windowScene
    didUpdateCoordinateSpace:(id<UICoordinateSpace>)previousCoordinateSpace
    interfaceOrientation:(UIInterfaceOrientation)previousInterfaceOrientation
    traitCollection:(UITraitCollection*)previousTraitCollection {
    (void)previousCoordinateSpace;
    (void)previousInterfaceOrientation;
    (void)previousTraitCollection;

    [self fitWindowToScene:windowScene];
}

- (void)scene:(UIScene*)scene openURLContexts:(NSSet<UIOpenURLContext*>*)URLContexts {
    (void)scene;

    for (UIOpenURLContext* context in URLContexts) {
        MobStoreDeepLinkURL(context.URL);
    }
}

@end

@interface AppDelegate : UIResponder <UIApplicationDelegate, UNUserNotificationCenterDelegate>
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication*)app
    didFinishLaunchingWithOptions:(NSDictionary*)opts {
    (void)app;

    [UNUserNotificationCenter currentNotificationCenter].delegate = self;

    // Must run before mob_init_ui() so the registry has every plugin view
    // factory in place by the time the BEAM mounts its first screen.
    mob_register_plugins();

    mob_init_ui();

    MobStoreLaunchNotificationUserInfo(opts[UIApplicationLaunchOptionsRemoteNotificationKey]);

    extern const char* mob_app_module(void);
    pthread_t t;
    pthread_create(&t, NULL, beam_thread, (void*)mob_app_module());
    pthread_detach(t);

    return YES;
}

- (void)userNotificationCenter:(UNUserNotificationCenter*)center
       willPresentNotification:(UNNotification*)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler {
    (void)center;

    MobStoreLaunchNotificationUserInfo(notification.request.content.userInfo);

    UNNotificationPresentationOptions options =
        UNNotificationPresentationOptionSound |
        UNNotificationPresentationOptionBanner |
        UNNotificationPresentationOptionList;

    completionHandler(options);
}

- (void)userNotificationCenter:(UNUserNotificationCenter*)center
didReceiveNotificationResponse:(UNNotificationResponse*)response
         withCompletionHandler:(void (^)(void))completionHandler {
    (void)center;

    MobStoreLaunchNotificationUserInfo(response.notification.request.content.userInfo);
    completionHandler();
}

- (UISceneConfiguration*)application:(UIApplication*)application
    configurationForConnectingSceneSession:(UISceneSession*)connectingSceneSession
    options:(UISceneConnectionOptions*)options {
    (void)application;
    (void)options;

    UISceneConfiguration* configuration =
        [[UISceneConfiguration alloc] initWithName:@"Default Configuration"
                                      sessionRole:connectingSceneSession.role];
    configuration.delegateClass = [SceneDelegate class];
    return configuration;
}

- (BOOL)application:(UIApplication*)app
    openURL:(NSURL*)url
    options:(NSDictionary<UIApplicationOpenURLOptionsKey, id>*)options {
    (void)app;
    (void)options;

    return MobStoreDeepLinkURL(url);
}

- (void)application:(UIApplication*)app
    didRegisterForRemoteNotificationsWithDeviceToken:(NSData*)deviceToken {
    // Convert token bytes to hex string and deliver to Elixir via NIF.
    NSMutableString* hex = [NSMutableString stringWithCapacity:deviceToken.length * 2];
    const unsigned char* bytes = (const unsigned char*)deviceToken.bytes;
    for (NSUInteger i = 0; i < deviceToken.length; i++) {
        [hex appendFormat:@"%02x", bytes[i]];
    }
    mob_send_push_token([hex UTF8String]);
}

- (void)application:(UIApplication*)app
    didFailToRegisterForRemoteNotificationsWithError:(NSError*)error {
    NSLog(@"[Mob] Failed to register for remote notifications: %@", error);
    NSString* reason = error.localizedDescription ?: @"unknown";
    mob_send_push_token_error([reason UTF8String]);
}

@end

int main(int argc, char* argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, @"AppDelegate");
    }
}
