defmodule Mix.Tasks.DevIde.Artifact.Smoke do
  @shortdoc "Create a static Artifact Project smoke preview"

  @moduledoc """
  Creates a static Artifact Project in a Git worktree for an existing workspace.

      mix dev_ide.artifact.smoke WORKSPACE_ID
      mix dev_ide.artifact.smoke --workspace WORKSPACE_ID --name "Milk Dashboard"
      mix dev_ide.artifact.smoke WORKSPACE_ID --serve --json

  The task prints the artifact id, worktree, runtime preview URL, and the
  Preview MCP arguments an agent can use to open the generated runtime surface.
  """

  use Mix.Task

  alias DevIDE.ArtifactProjects

  @impl true
  def run(argv) do
    Mix.Task.run("app.config")
    {:ok, _apps} = Application.ensure_all_started(:dev_ide)

    {opts, args, invalid} =
      OptionParser.parse(argv,
        strict: [
          workspace: :string,
          name: :string,
          prompt: :string,
          serve: :boolean,
          json: :boolean
        ],
        aliases: [w: :workspace, n: :name, p: :prompt]
      )

    if invalid != [] do
      Mix.raise("invalid option(s): #{Enum.map_join(invalid, ", ", &elem(&1, 0))}")
    end

    workspace_id =
      opts[:workspace] ||
        List.first(args) ||
        Mix.raise("workspace id is required")

    attrs = %{
      name: opts[:name] || default_name(),
      prompt: opts[:prompt] || "Smoke artifact generated by mix dev_ide.artifact.smoke."
    }

    with {:ok, project} <- ArtifactProjects.create(workspace_id, attrs),
         {:ok, project} <- maybe_serve(project, opts[:serve]) do
      print(project, opts[:json])
    else
      {:error, reason} -> Mix.raise("artifact smoke failed: #{inspect(reason)}")
      other -> Mix.raise("artifact smoke failed: #{inspect(other)}")
    end
  end

  defp maybe_serve(project, true), do: ArtifactProjects.serve(project.id)
  defp maybe_serve(project, _serve?), do: {:ok, project}

  defp print(project, true) do
    project
    |> ArtifactProjects.payload()
    |> Jason.encode!(pretty: true)
    |> Mix.shell().info()
  end

  defp print(project, _json?) do
    data = ArtifactProjects.payload(project)

    Mix.shell().info("""
    Artifact project created
      id: #{data.id}
      name: #{data.name}
      workspace_id: #{data.workspace_id}
      worktree: #{data.worktree_path}
      preview_url: #{data.preview_url}

    Preview MCP:
      preview_open(%{"workspace_id" => "#{data.workspace_id}", "mode" => "app", "runtime_id" => "#{data.runtime_id}"})
    """)
  end

  defp default_name do
    "Artifact Smoke #{DateTime.utc_now() |> DateTime.truncate(:second) |> DateTime.to_iso8601()}"
  end
end
