defmodule DevIDE do
  @moduledoc """
  Boundary root for the DevIDE domain contexts (`DevIDE.*`): terminals,
  audit, workspaces, policy, agents, preview, and friends.

  The domain layer may depend on the repo (`DevIDE.Repo`, its own
  boundary) but never on the web layer (`DevIdeWeb`) or the application
  shell (`DevIde`). The `boundary` compiler enforces this at build time;
  violations surface as compile warnings, which `mix precommit` promotes
  to errors.

  Note the namespace split is historical: `DevIDE.*` holds the domain,
  `DevIDE.*` holds app infrastructure generated by `phx.new`.
  """

  use Boundary,
    deps: [
      DevIDE.Repo,
      TmuxCtl,
      PreviewCtl,
      TerminalCtl,
      GitCtl,
      ExecCtl,
      McpCtl
    ],
    exports: :all
end
