defmodule DevIDE do
  @moduledoc """
  Boundary root for the DevIDE domain contexts (`DevIDE.*`): terminals,
  fleet, runners, assignments, audit, workspaces, policy, and friends.

  The domain layer may depend on the repo (`DevIde.Repo`, its own
  boundary) but never on the web layer (`DevIdeWeb`) or the application
  shell (`DevIde`). The `boundary` compiler enforces this at build time;
  violations surface as compile warnings, which `mix precommit` promotes
  to errors.

  Note the namespace split is historical: `DevIDE.*` holds the domain,
  `DevIde.*` holds app infrastructure generated by `phx.new`.
  """

  use Boundary,
    deps: [DevIde.Repo],
    exports: :all
end
