import Config

truthy? = fn value ->
  value in ~w(1 true TRUE yes YES on ON)
end

falsey? = fn value ->
  value in ~w(0 false FALSE no NO off OFF)
end

# Configure your database
# Supports DATABASE_URL for easy docker/local Postgres (e.g. when host port 5432 is taken)
sqlite_repo? =
  System.get_env("CASEIN_REPO_ADAPTER", "postgres")
  |> String.downcase()
  |> then(&(&1 in ["sqlite", "sqlite3"]))

if sqlite_repo? do
  config :casein, Casein.Repo,
    database:
      System.get_env("DATABASE_PATH") ||
        Path.expand("../dev_ide_dev.sqlite3", System.tmp_dir!()),
    journal_mode: :delete,
    pool_size: String.to_integer(System.get_env("POOL_SIZE") || "1"),
    busy_timeout: String.to_integer(System.get_env("SQLITE_BUSY_TIMEOUT_MS") || "5000"),
    stacktrace: true,
    show_sensitive_data_on_connection_error: true
else
  if System.get_env("DATABASE_URL") do
    config :casein, Casein.Repo, url: System.get_env("DATABASE_URL")
  else
    config :casein, Casein.Repo,
      username: "postgres",
      password: "postgres",
      hostname: "localhost",
      database: "dev_ide_dev",
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: 10
  end
end

# Run the dev server's tmux sessions on their own server (`tmux -L casein_dev`),
# distinct from prod's `devide` (config/prod.exs) and test's `devide_test`
# (config/test.exs). On the devbox the :4000 mix dev server and the release run
# as the same user, so a shared label would collide on one socket. Resolved by
# Casein.Terminals.TmuxServer.
config :casein, :tmux_server_label, "devide_dev"

# Slice 3 rollout ladder step 1: event-driven tmux topology ON in dev.
# Canary soak + prod default stay operational (watch TmuxEventsFlapWatch
# telemetry / flap alarm; flip via DEVIDE_TMUX_EVENTS). runtime.exs env
# overrides both ways when set. Test env stays OFF for flag-off no-op proofs.
config :casein, :tmux_events, true

devide_lan_requested? = truthy?.(System.get_env("CASEIN_LAN"))
devide_lan_insecure_http? = truthy?.(System.get_env("CASEIN_LAN_INSECURE_HTTP"))
devide_lan? = devide_lan_requested? or devide_lan_insecure_http?

devide_lan_hostname =
  case :inet.gethostname() do
    {:ok, hostname} ->
      hostname
      |> List.to_string()
      |> String.split(".")
      |> List.first()

    {:error, _} ->
      "localhost"
  end

devide_lan_mdns_host =
  if String.ends_with?(devide_lan_hostname, ".local") do
    devide_lan_hostname
  else
    "#{devide_lan_hostname}.local"
  end

devide_lan_host =
  System.get_env("CASEIN_LAN_HOST") ||
    devide_lan_mdns_host

devide_http_port = String.to_integer(System.get_env("PORT") || "4000")
devide_lan_https_port = String.to_integer(System.get_env("CASEIN_LAN_HTTPS_PORT") || "4443")

devide_lan_insecure_http_port =
  String.to_integer(System.get_env("CASEIN_LAN_INSECURE_HTTP_PORT") || "80")

devide_lan_certfile =
  System.get_env("CASEIN_LAN_CERTFILE") ||
    Path.expand("../priv/cert/casein-lan.pem", __DIR__)

devide_lan_keyfile =
  System.get_env("CASEIN_LAN_KEYFILE") ||
    Path.expand("../priv/cert/casein-lan-key.pem", __DIR__)

devide_lan_https? = devide_lan_requested? and not falsey?.(System.get_env("CASEIN_LAN_HTTPS"))

devide_endpoint_config = [
  # HTTP stays loopback-only; LAN mode adds a trusted HTTPS listener below.
  http: [ip: {127, 0, 0, 1}, port: devide_http_port],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IG4EOlcBEwImKOlB6OwEc8r/O1dn4NjtGBJU7VV0w0iQv8v839fWk7PZLzP39/86",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:casein, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:casein, ~w(--watch)]}
  ]
]

devide_endpoint_config =
  if devide_lan? do
    Keyword.put(devide_endpoint_config, :url,
      host: devide_lan_host,
      port:
        if(devide_lan_insecure_http?,
          do: devide_lan_insecure_http_port,
          else: devide_lan_https_port
        ),
      scheme: if(devide_lan_insecure_http?, do: "http", else: "https")
    )
  else
    devide_endpoint_config
  end

devide_endpoint_config =
  if devide_lan_https? do
    Keyword.put(devide_endpoint_config, :https,
      ip: {0, 0, 0, 0},
      port: devide_lan_https_port,
      cipher_suite: :strong,
      keyfile: devide_lan_keyfile,
      certfile: devide_lan_certfile
    )
  else
    devide_endpoint_config
  end

# For development, we disable any cache and enable
# debugging and code reloading.
#
config :casein, CaseinWeb.Endpoint, devide_endpoint_config

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

if devide_lan? do
  config :casein, :lan_mode, true

  if devide_lan_insecure_http? do
    config :casein, :lan_insecure_http, true
    config :casein, :session_same_site, nil
  end

  config :casein, :default_workspace, System.get_env("CASEIN_DEFAULT_WORKSPACE") || "home"
else
  if default_workspace = System.get_env("CASEIN_DEFAULT_WORKSPACE") do
    config :casein, :default_workspace, default_workspace
  end
end

case System.get_env("CASEIN_LAN_PATH_ROOT") do
  path when is_binary(path) and path != "" ->
    config :casein, :lan_path_root, path

  _ ->
    :ok
end

# Reload browser tabs when matching files change.
config :casein, CaseinWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/casein_web/router\.ex$"E,
      ~r"lib/casein_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :casein, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Pin the seed workspaces into :manual mode so "Raw shell" is
# selectable in the terminal tab (raw requires manual + local host).
config :casein, :workspace_modes, %{"alpha" => :manual, "home" => :manual}

# Local workspace source root — `/tmp/...` is always writable by the
# developer running `mix phx.server`, so the picker renders without
# requiring `/workspaces` to exist with special perms. The default
# `Casein.WorkspaceSource.Local` discovers subdirectories here as
# workspaces.
# Honors CASEIN_WORKSPACES_ROOT so an isolated preview instance
# (scripts/dev-preview-instance.sh) can point at a persistent seed root.
# The prod block in runtime.exs reads the same env var.
config :casein,
       :workspaces_root,
       System.get_env("CASEIN_WORKSPACES_ROOT") || "/tmp/casein_workspaces"

case System.get_env("CASEIN_HOME_WORKSPACE_PATH") do
  home_workspace_path when is_binary(home_workspace_path) and home_workspace_path != "" ->
    config :casein, :home_workspace_path, home_workspace_path

    config :casein,
           :lan_path_root,
           System.get_env("CASEIN_LAN_PATH_ROOT") || home_workspace_path

  _ ->
    :ok
end

config :casein,
  preview_control_adapter: :playwright,
  preview_playwright_script: "priv/scripts/preview_playwright.mjs",
  preview_artifacts_root: Path.expand("priv/preview_artifacts")
