import Config

# Configure your database
# Supports DATABASE_URL for easy docker/local Postgres (e.g. when host port 5432 is taken)
if System.get_env("DATABASE_URL") do
  config :dev_ide, DevIde.Repo, url: System.get_env("DATABASE_URL")
else
  config :dev_ide, DevIde.Repo,
    username: "postgres",
    password: "postgres",
    hostname: "localhost",
    database: "dev_ide_dev",
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :dev_ide, DevIdeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IG4EOlcBEwImKOlB6OwEc8r/O1dn4NjtGBJU7VV0w0iQv8v839fWk7PZLzP39/86",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:dev_ide, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:dev_ide, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :dev_ide, DevIdeWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/dev_ide_web/router\.ex$"E,
      ~r"lib/dev_ide_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :dev_ide, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Pin the seed workspace "alpha" into :manual mode so "Raw shell" is
# selectable in the terminal tab (raw requires manual + local host).
config :dev_ide, :workspace_modes, %{"alpha" => :manual}

# Local workspace source root — `/tmp/...` is always writable by the
# developer running `mix phx.server`, so the picker renders without
# requiring `/workspaces` to exist with special perms. The default
# `DevIDE.WorkspaceSource.Local` discovers subdirectories here as
# workspaces.
config :dev_ide, :workspaces_root, "/tmp/dev_ide_workspaces"

config :dev_ide,
  preview_control_adapter: :playwright,
  preview_playwright_script: "priv/scripts/preview_playwright.mjs",
  preview_artifacts_root: Path.expand("priv/preview_artifacts")
