import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :dev_ide, CaseinWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"
config :dev_ide, :secure_session_cookie, true

# SSL forcing is installed by CaseinWeb.RuntimeSSLPlug and configured from
# config/runtime.exs so a release can opt into the local LAN HTTP profile at
# service start without rebuilding the artifact.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Run Casein's tmux sessions on a dedicated server (`tmux -L devide`) instead of
# the host's default server. This isolates dev_ide-managed sessions from any
# plain SSH user's `tmux` (which uses the default socket), and lets the two
# carry different configs: dev_ide host sessions load priv/tmux/devide.conf via
# `-f`, while an SSH user keeps their own ~/.tmux.conf on the default server.
# Resolved by Casein.Terminals.TmuxServer. Must differ from the dev label
# (config/dev.exs) so the :4000 dev server and the release don't share a socket.
config :dev_ide, :tmux_server_label, "devide"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
