#!/usr/bin/env python3
"""Prepare an isolated Grok home for a Casein-managed leader."""

from __future__ import annotations

import json
import os
import re
import stat
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


LEADER_ID = re.compile(r"^[0-9a-f]{24}$")
LEGACY_AUTH_SCOPE = "https://accounts.x.ai/sign-in"
API_KEY_SCOPE = "xai::api_key"
SCRUBBED_ENV = (
    "XAI_API_KEY",
    "GROK_CODE_XAI_API_KEY",
    "GROK_AUTH",
    "GROK_AUTH_PATH",
    "GROK_AUTH_PROVIDER_COMMAND",
    "CASEIN_API_TOKEN",
    "CASEIN_ADMIN_API_TOKEN",
    "CASEIN_WORKSPACE_API_TOKENS",
    "CASEIN_GROK_XAI_API_KEY",
)
MINIMUM_ACCESS_TTL_SECONDS = 10 * 60
CONFIG = (
    "# Generated by Casein for one managed Grok leader.\n"
    "# The shell prefix prevents model-authored commands from inheriting credentials.\n"
    "[toolset.bash]\n"
    f'cmd_prefix = "unset {" ".join(SCRUBBED_ENV)}"\n'
)
SANDBOX = "# Casein rewrites this file before every managed Grok launch.\n"


class ManagedHomeError(ValueError):
    """A managed path or credential did not meet the fail-closed contract."""


def main() -> int:
    try:
        if len(sys.argv) == 4 and sys.argv[1] == "prepare":
            print(prepare_home(sys.argv[2], sys.argv[3]))
            return 0

        if len(sys.argv) == 4 and sys.argv[1] == "resolve":
            print(resolve_home(sys.argv[2], sys.argv[3]))
            return 0

        if len(sys.argv) in {2, 3} and sys.argv[1] == "access-key":
            scope = sys.argv[2] if len(sys.argv) == 3 else None
            print(read_access_key(scope))
            return 0

        if len(sys.argv) in {2, 3} and sys.argv[1] == "auth-json":
            scope = sys.argv[2] if len(sys.argv) == 3 else None
            print(read_auth_json(scope))
            return 0

        print(
            "usage: grok-managed-home.py prepare <absolute-root> <leader-id>\n"
            "       grok-managed-home.py resolve <absolute-root> <leader-id>\n"
            "       grok-managed-home.py access-key [scope]\n"
            "       grok-managed-home.py auth-json [scope]",
            file=sys.stderr,
        )
        return 2
    except (ManagedHomeError, OSError, UnicodeError, json.JSONDecodeError) as error:
        # Errors intentionally contain no auth entry values.
        print(f"error: {error}", file=sys.stderr)
        return 2


def prepare_home(root_value: str, leader_id: str) -> Path:
    """Create or reset the exact per-leader home and return its path."""

    if not LEADER_ID.fullmatch(leader_id):
        raise ManagedHomeError("invalid managed Grok leader id")

    root = safe_absolute_path(root_value, "managed Grok home root")
    if root == Path(root.anchor):
        raise ManagedHomeError("managed Grok home root cannot be a filesystem root")

    reject_symlink_components(root)
    mkdir_private(root)

    managed_home = root / leader_id
    reject_symlink_components(managed_home)
    mkdir_private(managed_home)

    ensure_private_sessions(managed_home / "sessions")

    atomic_fixed_write(managed_home / "config.toml", CONFIG)
    atomic_fixed_write(managed_home / "sandbox.toml", SANDBOX)
    # Grok receives refreshable OAuth through its documented read-only
    # GROK_AUTH seam. Keep a stable existing path for the sandbox to bind over;
    # refresh persistence fails closed while the in-memory credential rotates.
    atomic_fixed_write(managed_home / "auth.json", "{}\n")
    return managed_home


def resolve_home(root_value: str, leader_id: str) -> Path:
    """Validate an existing managed home without touching a live leader's files."""

    if not LEADER_ID.fullmatch(leader_id):
        raise ManagedHomeError("invalid managed Grok leader id")
    root = safe_absolute_path(root_value, "managed Grok home root")
    managed_home = root / leader_id
    reject_symlink_components(managed_home)
    for path in (root, managed_home):
        try:
            file_stat = path.lstat()
        except FileNotFoundError as error:
            raise ManagedHomeError("managed Grok home is missing") from error
        if (
            not stat.S_ISDIR(file_stat.st_mode)
            or stat.S_ISLNK(file_stat.st_mode)
            or file_stat.st_uid != os.getuid()
            or stat.S_IMODE(file_stat.st_mode) & 0o077
        ):
            raise ManagedHomeError("managed Grok home is not private and owned")
    return managed_home


def safe_absolute_path(value: str, label: str) -> Path:
    if not value or "\x00" in value:
        raise ManagedHomeError(f"invalid {label}")

    expanded = Path(os.path.expanduser(value))
    if not expanded.is_absolute():
        raise ManagedHomeError(f"{label} must be absolute")

    normalized = Path(os.path.abspath(expanded))
    if expanded != normalized:
        raise ManagedHomeError(f"{label} must be normalized")
    return normalized


def reject_symlink_components(path: Path) -> None:
    """Reject an existing symlink anywhere in a managed path."""

    current = Path(path.anchor)
    for component in path.parts[1:]:
        current /= component
        try:
            mode = current.lstat().st_mode
        except FileNotFoundError:
            continue
        if stat.S_ISLNK(mode):
            raise ManagedHomeError(f"managed path contains a symlink: {current}")


def mkdir_private(path: Path) -> None:
    try:
        mode = path.lstat().st_mode
    except FileNotFoundError:
        path.mkdir(parents=True, mode=0o700)
        mode = path.lstat().st_mode

    if not stat.S_ISDIR(mode) or stat.S_ISLNK(mode):
        raise ManagedHomeError(f"managed path is not a private directory: {path}")
    os.chmod(path, 0o700)


def persistent_sessions_path() -> Path:
    home_value = os.environ.get("HOME")
    if not home_value:
        raise ManagedHomeError("HOME is required for persistent Grok sessions")

    home = safe_absolute_path(home_value, "HOME")
    reject_symlink_components(home)
    grok_home = home / ".grok"
    reject_symlink_components(grok_home)
    mkdir_private(grok_home)
    return grok_home / "sessions"


def ensure_private_sessions(path: Path) -> None:
    try:
        mode = path.lstat().st_mode
    except FileNotFoundError:
        path.mkdir(mode=0o700)
        mode = path.lstat().st_mode

    if stat.S_ISLNK(mode):
        # Migrate only Casein's former canonical global-sessions link. Never
        # follow or replace an attacker-selected link.
        if os.readlink(path) != str(persistent_sessions_path()):
            raise ManagedHomeError("managed sessions symlink has an unexpected target")
        path.unlink()
        path.mkdir(mode=0o700)
        mode = path.lstat().st_mode

    if not stat.S_ISDIR(mode):
        raise ManagedHomeError("managed sessions path is not a directory")
    os.chmod(path, 0o700)


def atomic_fixed_write(path: Path, content: str) -> None:
    try:
        mode = path.lstat().st_mode
    except FileNotFoundError:
        pass
    else:
        if stat.S_ISLNK(mode) or not stat.S_ISREG(mode):
            raise ManagedHomeError(f"managed file was replaced: {path.name}")

    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(tmp_name, 0o600)
        os.replace(tmp_name, path)
    finally:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass


def read_access_key(scope: str | None) -> str:
    """Return only a selected provider key from persistent auth.json."""

    return entry_key(select_auth_entry(scope)) or ""


def read_auth_json(scope: str | None) -> str:
    """Return one validated refreshable credential for GROK_AUTH."""

    entry = select_auth_entry(scope)
    if not refreshable_entry(entry):
        raise ManagedHomeError("selected Grok auth scope is not refreshable OIDC")
    return json.dumps(entry, separators=(",", ":"), sort_keys=True)


def select_auth_entry(scope: str | None) -> dict[str, Any]:
    """Select one current provider entry without including values in errors."""

    auth_path = persistent_auth_path()
    try:
        mode = auth_path.lstat().st_mode
    except FileNotFoundError as error:
        raise ManagedHomeError("persistent Grok auth.json is missing") from error
    if stat.S_ISLNK(mode) or not stat.S_ISREG(mode):
        raise ManagedHomeError("persistent Grok auth.json is not a regular file")

    with auth_path.open(encoding="utf-8") as handle:
        store = json.load(handle)
    if not isinstance(store, dict):
        raise ManagedHomeError("persistent Grok auth.json has an invalid shape")

    if scope is not None:
        entry = store.get(scope)
        key = entry_key(entry)
        if key is None:
            raise ManagedHomeError("requested Grok auth scope has no access key")
        return entry

    candidates = [
        (name, entry)
        for name, entry in store.items()
        if name != API_KEY_SCOPE
        and isinstance(entry, dict)
        and str(entry.get("auth_mode", "")).lower() != "web_login"
        and entry_key(entry) is not None
        and valid_for_launch(entry)
    ]
    if len(candidates) == 1:
        return candidates[0][1]

    # A unique newest credential matches Grok's normal replacement behavior.
    dated = [(parse_time(entry.get("create_time")), name, entry) for name, entry in candidates]
    dated = [candidate for candidate in dated if candidate[0] is not None]
    dated.sort(key=lambda candidate: candidate[0], reverse=True)
    if dated and (len(dated) == 1 or dated[0][0] != dated[1][0]):
        return dated[0][2]

    legacy = [(name, entry) for name, entry in candidates if name == LEGACY_AUTH_SCOPE]
    if len(legacy) == 1:
        return legacy[0][1]

    if not candidates:
        raise ManagedHomeError("persistent Grok auth.json has no current provider access key")
    raise ManagedHomeError("persistent Grok auth.json is ambiguous; provide an auth scope")


def refreshable_entry(entry: Any) -> bool:
    if not isinstance(entry, dict):
        return False
    return (
        str(entry.get("auth_mode", "")).lower() == "oidc"
        and isinstance(entry.get("refresh_token"), str)
        and bool(entry["refresh_token"].strip())
        and isinstance(entry.get("oidc_issuer"), str)
        and bool(entry["oidc_issuer"].strip())
        and isinstance(entry.get("oidc_client_id"), str)
        and bool(entry["oidc_client_id"].strip())
    )


def persistent_auth_path() -> Path:
    home_value = os.environ.get("HOME")
    if not home_value:
        raise ManagedHomeError("HOME is required for persistent Grok auth")
    home = safe_absolute_path(home_value, "HOME")
    reject_symlink_components(home / ".grok")
    return home / ".grok" / "auth.json"


def entry_key(entry: Any) -> str | None:
    if not isinstance(entry, dict):
        return None
    key = entry.get("key")
    if not isinstance(key, str) or not key or key != key.strip():
        return None
    if any(character.isspace() or ord(character) < 32 for character in key):
        return None
    return key


def valid_for_launch(entry: dict[str, Any]) -> bool:
    expires_at = parse_time(entry.get("expires_at"))
    return (
        expires_at is not None
        and (expires_at - datetime.now(timezone.utc)).total_seconds()
        >= MINIMUM_ACCESS_TTL_SECONDS
    )


def parse_time(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


if __name__ == "__main__":
    raise SystemExit(main())
