defmodule DevIdeWeb.ChannelAuth do
  @moduledoc """
  Centralised auth helpers for Phoenix channels.

  All channel-related token signing/verification flows through this module so
  the salt and max-age live in one place. When real auth lands, this is the
  module to extend, not the LiveViews and channels.
  """

  @user_socket_salt "user socket"
  @terminal_workspace_salt "terminal workspace"
  @max_age 86_400
  # The terminal capability lets a channel join skip the manager workspace
  # re-check (it grants raw-shell access), so it gets a much shorter life than the
  # session token — a captured/replayed capability is only useful for minutes,
  # not a day. It's minted fresh on every LiveView mount, so a short window is
  # plenty for the join that immediately follows.
  @terminal_capability_max_age 900

  @doc """
  Sign a channel token carrying the authenticated identity.

  Email is needed because channels forward auth to the workspace source
  (`Workspaces.get/2` etc.) as `x-auth-request-email`. The source derives
  the username server-side but only accepts the email — not a username —
  as the auth header. Without `email`, channel calls hit the source
  unauthed and get rejected → `REFUSED JOIN`.
  """
  def sign_user_token(user_id, email \\ nil)
      when is_binary(user_id) and (is_binary(email) or is_nil(email)) do
    Phoenix.Token.sign(DevIdeWeb.Endpoint, @user_socket_salt, %{id: user_id, email: email})
  end

  @doc """
  Verify a channel token. Returns `{:ok, user_id, email}` on success.

  Tolerates legacy tokens that signed just the user_id binary (pre-email
  rollout) by returning `{:ok, id, nil}` — those still work for channels
  that don't need manager auth, and surface as a regular auth failure for
  those that do.
  """
  def verify_user_token(token) when is_binary(token) and byte_size(token) > 0 do
    case Phoenix.Token.verify(DevIdeWeb.Endpoint, @user_socket_salt, token, max_age: @max_age) do
      {:ok, %{id: id, email: email}} when is_binary(id) -> {:ok, id, email}
      # Legacy: token from before the email round-trip landed.
      {:ok, id} when is_binary(id) -> {:ok, id, nil}
      err -> err
    end
  end

  def verify_user_token(_), do: {:error, :missing}

  @doc """
  Sign a lightweight terminal join capability for a specific workspace.

  This token lets a channel join take a fast path after the same
  LiveView render has already validated access for the same workspace.
  """
  def sign_terminal_capability(user_id, workspace_id, opts \\ [])
      when is_binary(user_id) and is_binary(workspace_id) do
    claims =
      [
        kind: :terminal_workspace,
        user_id: user_id,
        workspace_id: workspace_id,
        issued_at: System.system_time(:second)
      ]
      |> Keyword.merge(opts)
      |> Map.new()

    Phoenix.Token.sign(DevIdeWeb.Endpoint, @terminal_workspace_salt, claims)
  end

  @doc """
  Verify a terminal join capability generated by `sign_terminal_capability/3`.
  """
  def verify_terminal_capability(token) when is_binary(token) and byte_size(token) > 0 do
    with {:ok, claims} <-
           Phoenix.Token.verify(DevIdeWeb.Endpoint, @terminal_workspace_salt, token,
             max_age: @terminal_capability_max_age
           ) do
      claims = normalize_terminal_claims(claims)

      case claims do
        %{kind: :terminal_workspace, user_id: user_id, workspace_id: workspace_id}
        when is_binary(user_id) and is_binary(workspace_id) ->
          {:ok, claims}

        _ ->
          {:error, :invalid_terminal_capability}
      end
    end
  end

  def verify_terminal_capability(_), do: {:error, :missing}

  defp normalize_terminal_claims(claims) when is_list(claims), do: Map.new(claims)
  defp normalize_terminal_claims(claims), do: claims
end
