defmodule DevIdeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :dev_ide

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_dev_ide_key",
    signing_salt: "9/grDa2y",
    same_site: "Lax",
    secure: Application.compile_env(:dev_ide, :secure_session_cookie, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/socket", DevIdeWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :dev_ide,
    gzip: not code_reloading?,
    only: DevIdeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :dev_ide
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {__MODULE__, :cache_preview_proxy_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DevIdeWeb.Router

  @doc false
  def cache_preview_proxy_body(conn, opts) do
    case Plug.Conn.read_body(conn, opts) do
      {:ok, body, conn} ->
        {:ok, body, maybe_cache_preview_proxy_body(conn, body)}

      {:more, body, conn} ->
        {:more, body, maybe_cache_preview_proxy_body(conn, body)}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp maybe_cache_preview_proxy_body(%{request_path: "/preview-proxy/" <> _} = conn, body)
       when is_binary(body) do
    Plug.Conn.put_private(conn, :devide_preview_proxy_raw_body, body)
  end

  defp maybe_cache_preview_proxy_body(conn, _body), do: conn
end
