#!/usr/bin/env bash
#
# Materialize per-workspace MCP client configs for external agents (Grok, Claude,
# Codex, OpenCode, Cursor). Reads .devbox-agent.env (or already-exported vars).
# Does not replace global agent homes. DevIDE MCP is injected by the launcher
# using project-local config files or per-launch overrides.
#
# Usage:
#   source .devbox-agent.env
#   bash scripts/materialize-agent-mcp.sh
#
# Exports DEVIDE_AGENT_MCP_HOME on stdout-friendly assignment when sourced:
#   eval "$(bash scripts/materialize-agent-mcp.sh --export)"
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

EXPORT_ONLY=0
if [[ "${1:-}" == "--export" ]]; then
  EXPORT_ONLY=1
fi

if [[ -f "${ROOT}/.devbox-agent.env" ]] && [[ -z "${DEV_IDE_API_TOKEN:-}" ]]; then
  # shellcheck source=/dev/null
  source "${ROOT}/.devbox-agent.env"
fi

: "${DEV_IDE_API_TOKEN:?DEV_IDE_API_TOKEN is required (source .devbox-agent.env)}"
DEV_IDE_API_TOKEN="$(
  DEV_IDE_API_TOKEN="${DEV_IDE_API_TOKEN}" python3 -c "
import os
t = os.environ.get('DEV_IDE_API_TOKEN', '').strip()
if len(t) >= 2 and t[0] == t[-1] and t[0] in \"'\\\"\":
    t = t[1:-1]
print(t)
"
)"
: "${DEVIDE_WORKSPACE_NAME:?DEVIDE_WORKSPACE_NAME is required}"
: "${DEVIDE_WORKSPACE_ID:?DEVIDE_WORKSPACE_ID is required}"
: "${DEVIDE_TERMINAL_MCP_URL:?DEVIDE_TERMINAL_MCP_URL is required}"
: "${DEVIDE_PREVIEW_MCP_URL:?DEVIDE_PREVIEW_MCP_URL is required}"
: "${DEVIDE_TMUX_SESSION:=}"

if [[ -z "${DEVIDE_TIDEWAVE_MCP_URL:-}" ]]; then
  if [[ -x "${ROOT}/scripts/preview-env.sh" ]]; then
    DEVIDE_TIDEWAVE_MCP_URL="$(
      bash "${ROOT}/scripts/preview-env.sh" tidewave-latest 2>/dev/null || true
    )"
  fi
  if [[ -z "${DEVIDE_TIDEWAVE_MCP_URL:-}" ]] && [[ -x "${ROOT}/scripts/tidewave-resolve-url.sh" ]]; then
    DEVIDE_TIDEWAVE_MCP_URL="$(
      bash "${ROOT}/scripts/tidewave-resolve-url.sh" 2>/dev/null || true
    )"
  fi
fi

if [[ -z "${DEVIDE_CHECKOUT:-}" ]]; then
  case "${DEVIDE_WORKSPACE_NAME}" in
    dalexandre-devide) DEVIDE_CHECKOUT="${ROOT}" ;;
    *)
      if [[ -d "/data/workspaces/${DEVIDE_WORKSPACE_NAME}" ]]; then
        DEVIDE_CHECKOUT="/data/workspaces/${DEVIDE_WORKSPACE_NAME}"
      else
        DEVIDE_CHECKOUT="${ROOT}"
      fi
      ;;
  esac
fi
HOME_DIR="${HOME:?HOME is required}"
DEFAULT_STAGING="${HOME_DIR}/.devide/agent-mcp/${DEVIDE_WORKSPACE_NAME}"
if [[ -n "${DEVIDE_AGENT_MCP_HOME:-}" ]] && [[ "${DEVIDE_AGENT_MCP_HOME}" != "${DEFAULT_STAGING}" ]]; then
  unset DEVIDE_AGENT_MCP_HOME
fi
STAGING="${DEVIDE_AGENT_MCP_HOME:-${DEFAULT_STAGING}}"
export DEVIDE_AGENT_MCP_HOME="${STAGING}"

if [[ -f "${DEVIDE_CHECKOUT}/scripts/devide" ]]; then
  DEVIDE_SCRIPTS="${DEVIDE_CHECKOUT}/scripts"
else
  DEVIDE_SCRIPTS="${DEVIDE_SCRIPTS:-${ROOT}/scripts}"
fi
export DEVIDE_SCRIPTS

mkdir -p "${STAGING}/grok" "${STAGING}/codex" "${STAGING}/cursor"

WORKSPACE_SLUG="$(
  DEVIDE_WORKSPACE_NAME="${DEVIDE_WORKSPACE_NAME}" python3 -c "
import os, re
slug = re.sub(r'[^a-zA-Z0-9]+', '-', os.environ['DEVIDE_WORKSPACE_NAME']).strip('-').lower()
print(slug or 'workspace')
"
)"
TERMINAL_KEY="devide-terminal-${WORKSPACE_SLUG}"
PREVIEW_KEY="devide-preview-${WORKSPACE_SLUG}"
TIDEWAVE_KEY="devide-tidewave-${WORKSPACE_SLUG}"

TIDEWAVE_GROK_BLOCK=""
TIDEWAVE_OPENCODE_BLOCK=""
TIDEWAVE_ENV_EXPORT=""
if [[ -n "${DEVIDE_TIDEWAVE_MCP_URL:-}" ]]; then
  TIDEWAVE_GROK_BLOCK="
[mcp_servers.${TIDEWAVE_KEY}]
url = \"${DEVIDE_TIDEWAVE_MCP_URL}\"
enabled = true
"
  TIDEWAVE_OPENCODE_BLOCK=",
    \"${TIDEWAVE_KEY}\": {
      \"type\": \"remote\",
      \"url\": \"${DEVIDE_TIDEWAVE_MCP_URL}\",
      \"enabled\": true,
      \"oauth\": false
    }"
  printf -v TIDEWAVE_ENV_EXPORT 'export DEVIDE_TIDEWAVE_MCP_URL=%q' "${DEVIDE_TIDEWAVE_MCP_URL}"
fi

# --- Grok (GROK_HOME) ---
cat >"${STAGING}/grok/config.toml" <<EOF
# Generated by scripts/materialize-agent-mcp.sh — do not edit by hand.
[mcp_servers.${TERMINAL_KEY}]
url = "${DEVIDE_TERMINAL_MCP_URL}"
enabled = true

[mcp_servers.${TERMINAL_KEY}.headers]
Authorization = "Bearer \${DEV_IDE_API_TOKEN}"

[mcp_servers.${PREVIEW_KEY}]
url = "${DEVIDE_PREVIEW_MCP_URL}"
enabled = true

[mcp_servers.${PREVIEW_KEY}.headers]
Authorization = "Bearer \${DEV_IDE_API_TOKEN}"
${TIDEWAVE_GROK_BLOCK}
EOF

# --- Codex staging marker (launch-devide-agent.sh injects MCP at startup) ---
cat >"${STAGING}/codex/config.toml" <<EOF
# Generated by scripts/materialize-agent-mcp.sh — do not edit by hand.
# DevIDE MCP is injected into Codex by scripts/launch-devide-agent.sh with
# per-launch -c overrides. Keeping this file free of DevIDE MCP entries prevents
# plain Codex startups from requiring a DevIDE token in the environment.
EOF

# --- OpenCode (OPENCODE_CONFIG) ---
cat >"${STAGING}/opencode.json" <<EOF
{
  "\$schema": "https://opencode.ai/config.json",
  "mcp": {
    "${TERMINAL_KEY}": {
      "type": "remote",
      "url": "${DEVIDE_TERMINAL_MCP_URL}",
      "enabled": true,
      "oauth": false,
      "headers": {
        "Authorization": "Bearer {env:DEV_IDE_API_TOKEN}"
      }
    },
    "${PREVIEW_KEY}": {
      "type": "remote",
      "url": "${DEVIDE_PREVIEW_MCP_URL}",
      "enabled": true,
      "oauth": false,
      "headers": {
        "Authorization": "Bearer {env:DEV_IDE_API_TOKEN}"
      }
    }${TIDEWAVE_OPENCODE_BLOCK}
  }
}
EOF

# --- Universal .mcp.json (Claude project, Grok, Cursor compat) ---
python3 "${ROOT}/scripts/lib/merge-agent-mcp.py" write-claude-mcp \
  "${STAGING}/.mcp.json" "${DEVIDE_TERMINAL_MCP_URL}" "${DEVIDE_PREVIEW_MCP_URL}"
cp "${STAGING}/.mcp.json" "${STAGING}/cursor/mcp.json"

ENV_SH="${STAGING}/env.sh"
cat >"${ENV_SH}" <<EOF
# Generated by scripts/materialize-agent-mcp.sh — source or load via devide agent env.
export DEV_IDE_API_TOKEN='${DEV_IDE_API_TOKEN}'
export DEVIDE_WORKSPACE_ID='${DEVIDE_WORKSPACE_ID}'
export DEVIDE_WORKSPACE_NAME='${DEVIDE_WORKSPACE_NAME}'
export DEVIDE_TERMINAL_MCP_URL='${DEVIDE_TERMINAL_MCP_URL}'
export DEVIDE_PREVIEW_MCP_URL='${DEVIDE_PREVIEW_MCP_URL}'
export DEVIDE_TMUX_SESSION='${DEVIDE_TMUX_SESSION}'
${TIDEWAVE_ENV_EXPORT}
export DEVIDE_CHECKOUT='${DEVIDE_CHECKOUT}'
export DEVIDE_AGENT_MCP_HOME='${STAGING}'
export DEVIDE_SCRIPTS='${DEVIDE_SCRIPTS}'
export DEVIDE_AGENT_ENV_FILE='${ENV_SH}'
export PATH="${HOME}/.local/bin:\${PATH}"
EOF
chmod 600 "${ENV_SH}"

# Cursor project discovery: copy into checkout when writable (gitignored).
# Claude no longer uses a checkout .mcp.json — the launcher injects this
# workspace's isolated staging file via `claude --mcp-config`, so writing a
# shared-checkout project file (which collided across workspaces) is omitted.
if [[ -n "${DEVIDE_CHECKOUT}" ]] && [[ -d "${DEVIDE_CHECKOUT}" ]] && [[ -w "${DEVIDE_CHECKOUT}" ]]; then
  mkdir -p "${DEVIDE_CHECKOUT}/.cursor"
  cp "${STAGING}/cursor/mcp.json" "${DEVIDE_CHECKOUT}/.cursor/mcp.json"
  chmod 600 "${DEVIDE_CHECKOUT}/.cursor/mcp.json"
fi

python3 "${ROOT}/scripts/lib/merge-agent-mcp.py" 2>/dev/null || true

if [[ "$EXPORT_ONLY" -eq 1 ]]; then
  # The materialized .mcp.json (and grok/opencode configs) auth with the
  # literal placeholder `Bearer ${DEV_IDE_API_TOKEN}`, which the agent expands
  # from its process env. The launch wrapper eval's this output before exec'ing
  # the agent, so the token MUST be exported here or every server 401s.
  printf 'export DEV_IDE_API_TOKEN=%q\n' "$DEV_IDE_API_TOKEN"
  printf 'export DEVIDE_AGENT_MCP_HOME=%q\n' "$STAGING"
  printf 'export DEVIDE_CHECKOUT=%q\n' "$DEVIDE_CHECKOUT"
  printf 'export DEVIDE_AGENT_ENV_FILE=%q\n' "$ENV_SH"
  exit 0
fi

cat <<EOF
Materialized DevIDE MCP client configs for workspace: ${DEVIDE_WORKSPACE_NAME}
  staging:  ${STAGING}
  checkout: ${DEVIDE_CHECKOUT}

Agents (from any directory — shims on PATH after install-agent-shims.sh):
  grok
  claude
  codex
  opencode

MCP is injected into agents without replacing auth state.
DevIDE MCP is not persisted in global Grok/Codex/OpenCode config files.
EOF
