#!/usr/bin/env bash
#
# Materialize per-workspace MCP client configs for external agents (Grok, Claude,
# Codex, OpenCode, Cursor). Reads .devbox-agent.env (or already-exported vars).
# Does not touch global agent homes (~/.grok, ~/.codex, ~/.claude.json).
#
# Usage:
#   source .devbox-agent.env
#   bash scripts/materialize-agent-mcp.sh
#
# Exports DEVIDE_AGENT_MCP_HOME on stdout-friendly assignment when sourced:
#   eval "$(bash scripts/materialize-agent-mcp.sh --export)"
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

EXPORT_ONLY=0
if [[ "${1:-}" == "--export" ]]; then
  EXPORT_ONLY=1
fi

if [[ -f "${ROOT}/.devbox-agent.env" ]] && [[ -z "${DEV_IDE_API_TOKEN:-}" ]]; then
  # shellcheck source=/dev/null
  source "${ROOT}/.devbox-agent.env"
fi

: "${DEV_IDE_API_TOKEN:?DEV_IDE_API_TOKEN is required (source .devbox-agent.env)}"
: "${DEVIDE_WORKSPACE_NAME:?DEVIDE_WORKSPACE_NAME is required}"
: "${DEVIDE_TERMINAL_MCP_URL:?DEVIDE_TERMINAL_MCP_URL is required}"
: "${DEVIDE_PREVIEW_MCP_URL:?DEVIDE_PREVIEW_MCP_URL is required}"

DEVIDE_CHECKOUT="${DEVIDE_CHECKOUT:-$ROOT}"
HOME_DIR="${HOME:?HOME is required}"
STAGING="${DEVIDE_AGENT_MCP_HOME:-${HOME_DIR}/.devide/agent-mcp/${DEVIDE_WORKSPACE_NAME}}"

mkdir -p "${STAGING}/grok" "${STAGING}/codex" "${STAGING}/cursor"

# --- Grok (GROK_HOME) ---
cat >"${STAGING}/grok/config.toml" <<EOF
# Generated by scripts/materialize-agent-mcp.sh — do not edit by hand.
[mcp_servers.devide-terminal]
url = "${DEVIDE_TERMINAL_MCP_URL}"
enabled = true

[mcp_servers.devide-terminal.headers]
Authorization = "Bearer \${DEV_IDE_API_TOKEN}"

[mcp_servers.devide-preview]
url = "${DEVIDE_PREVIEW_MCP_URL}"
enabled = true

[mcp_servers.devide-preview.headers]
Authorization = "Bearer \${DEV_IDE_API_TOKEN}"
EOF

# --- Codex (CODEX_HOME) ---
cat >"${STAGING}/codex/config.toml" <<EOF
# Generated by scripts/materialize-agent-mcp.sh — do not edit by hand.
[mcp_servers.devide-terminal]
url = "${DEVIDE_TERMINAL_MCP_URL}"
enabled = true
bearer_token_env_var = "DEV_IDE_API_TOKEN"

[mcp_servers.devide-preview]
url = "${DEVIDE_PREVIEW_MCP_URL}"
enabled = true
bearer_token_env_var = "DEV_IDE_API_TOKEN"
EOF

# --- OpenCode (OPENCODE_CONFIG) ---
cat >"${STAGING}/opencode.json" <<EOF
{
  "\$schema": "https://opencode.ai/config.json",
  "mcp": {
    "devide-terminal": {
      "type": "remote",
      "url": "${DEVIDE_TERMINAL_MCP_URL}",
      "enabled": true,
      "oauth": false,
      "headers": {
        "Authorization": "Bearer {env:DEV_IDE_API_TOKEN}"
      }
    },
    "devide-preview": {
      "type": "remote",
      "url": "${DEVIDE_PREVIEW_MCP_URL}",
      "enabled": true,
      "oauth": false,
      "headers": {
        "Authorization": "Bearer {env:DEV_IDE_API_TOKEN}"
      }
    }
  }
}
EOF

# --- Universal .mcp.json (Claude project, Grok, Cursor compat) ---
# Token is expanded at materialize time into a gitignored staging/checkout file.
cat >"${STAGING}/.mcp.json" <<EOF
{
  "mcpServers": {
    "devide-terminal": {
      "type": "http",
      "url": "${DEVIDE_TERMINAL_MCP_URL}",
      "headers": {
        "Authorization": "Bearer ${DEV_IDE_API_TOKEN}"
      }
    },
    "devide-preview": {
      "type": "http",
      "url": "${DEVIDE_PREVIEW_MCP_URL}",
      "headers": {
        "Authorization": "Bearer ${DEV_IDE_API_TOKEN}"
      }
    }
  }
}
EOF

cp "${STAGING}/.mcp.json" "${STAGING}/cursor/mcp.json"

# Claude/Cursor project discovery: copy into checkout (gitignored).
if [[ -n "${DEVIDE_CHECKOUT}" ]] && [[ -d "${DEVIDE_CHECKOUT}" ]]; then
  cp "${STAGING}/.mcp.json" "${DEVIDE_CHECKOUT}/.mcp.json"
  chmod 600 "${DEVIDE_CHECKOUT}/.mcp.json"
  mkdir -p "${DEVIDE_CHECKOUT}/.cursor"
  cp "${STAGING}/cursor/mcp.json" "${DEVIDE_CHECKOUT}/.cursor/mcp.json"
  chmod 600 "${DEVIDE_CHECKOUT}/.cursor/mcp.json"
fi

if [[ "$EXPORT_ONLY" -eq 1 ]]; then
  printf 'export DEVIDE_AGENT_MCP_HOME=%q\n' "$STAGING"
  printf 'export DEVIDE_CHECKOUT=%q\n' "$DEVIDE_CHECKOUT"
  exit 0
fi

cat <<EOF
Materialized DevIDE MCP client configs for workspace: ${DEVIDE_WORKSPACE_NAME}
  staging:  ${STAGING}
  checkout: ${DEVIDE_CHECKOUT}

Runtimes (from any directory after sourcing .devbox-agent.env):
  bash scripts/launch-devide-agent.sh grok
  bash scripts/launch-devide-agent.sh codex
  bash scripts/launch-devide-agent.sh claude
  bash scripts/launch-devide-agent.sh opencode

Or set env yourself:
  GROK_HOME=${STAGING}/grok
  CODEX_HOME=${STAGING}/codex
  OPENCODE_CONFIG=${STAGING}/opencode.json
EOF
