#!/usr/bin/env bash
#
# preview-router.sh — dynamic reverse proxy for ephemeral preview environments.
#
# Generates a Caddyfile from the preview registry mapping
#   <id>.<PREVIEW_DOMAIN>  ->  127.0.0.1:<env-port>
# and runs/reloads a DEDICATED Caddy instance (its own admin port, no TLS). This
# is OUR instance — it never touches the devbox-manager Caddy.
#
# Edge hookup (one-time, devbox-manager side — NOT done here): point the
# *.devbox.milcgroup.com catch-all at this router so unmatched single-label
# subdomains (covered by the existing wildcard DNS + TLS cert) fall through:
#     handle { reverse_proxy 127.0.0.1:41080 }   # was: respond 404
# Then https://<id>.devbox.milcgroup.com routes straight to the env.
#
# Commands:
#   preview-router.sh reload    # regenerate from registry + start-or-reload
#   preview-router.sh stop
#   preview-router.sh status
#   preview-router.sh config    # print the generated Caddyfile
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE="${DEVIDE_PREVIEW_HOME:-$(dirname "$ROOT")/.devide-preview}"
INST_DIR="$STATE/instances"
ROUTER_DIR="$STATE/router"
CADDYFILE="$ROUTER_DIR/Caddyfile"
PIDFILE="$ROUTER_DIR/caddy.pid"
ROUTE_COUNT_FILE="$ROUTER_DIR/route-count"
LISTEN="${DEVIDE_PREVIEW_ROUTER_LISTEN:-:41080}"
ADMIN="${DEVIDE_PREVIEW_ROUTER_ADMIN:-127.0.0.1:41081}"
DOMAIN="${DEVIDE_PREVIEW_DOMAIN:-devbox.milcgroup.com}"

mkdir -p "$ROUTER_DIR"
json_get() { sed -n "s/.*\"$2\":\"\\([^\"]*\\)\".*/\\1/p" "$1"; }
pid_alive() { [ -n "$1" ] && kill -0 "$1" 2>/dev/null; }

record_active() {
  local f="$1" status pid socket
  status="$(json_get "$f" status)"
  pid="$(json_get "$f" pid)"
  socket="$(json_get "$f" socket)"

  [ "$status" = running ] || return 1
  pid_alive "$pid" || return 1
  [ -z "$socket" ] || [ -S "$socket" ]
}

generate() {
  local n=0
  {
    echo "{"
    echo "    admin $ADMIN"
    echo "    auto_https off"
    echo "}"
    echo
    echo "# Generated by preview-router.sh from $INST_DIR — do not edit by hand."
    echo "$LISTEN {"
    shopt -s nullglob
    local f
    for f in "$INST_DIR"/*.json; do
      local id port socket upstream
      record_active "$f" || continue
      id="$(json_get "$f" id)"; port="$(json_get "$f" port)"; socket="$(json_get "$f" socket)"
      [ -n "$id" ] || continue
      # Prefer the unix socket (collision-free, the canonical front door); fall
      # back to the loopback port for older registry records without a socket.
      if [ -n "$socket" ]; then
        upstream="unix/$socket"
      elif [ -n "$port" ]; then
        upstream="127.0.0.1:$port"
      else
        continue
      fi
      printf '    @%s host %s.%s\n' "$id" "$id" "$DOMAIN"
      printf '    handle @%s {\n        reverse_proxy %s\n    }\n' "$id" "$upstream"
      n=$((n+1))
    done
    echo '    handle {'
    echo '        respond "No active preview environment for {host}" 404'
    echo '    }'
    echo "}"
  } > "$CADDYFILE"
  printf '%s\n' "$n" > "$ROUTE_COUNT_FILE"
}

admin_alive() { curl -s --max-time 2 "http://$ADMIN/config/" >/dev/null 2>&1; }

cmd_reload() {
  generate
  caddy validate --adapter caddyfile --config "$CADDYFILE" >/dev/null 2>&1 \
    || { echo "error: generated Caddyfile failed validation" >&2; caddy validate --adapter caddyfile --config "$CADDYFILE"; exit 1; }
  if admin_alive; then
    caddy reload --adapter caddyfile --config "$CADDYFILE" --address "$ADMIN" >/dev/null 2>&1
    echo "router reloaded ($(cat "$ROUTE_COUNT_FILE" 2>/dev/null || echo 0) active env(s)) on $LISTEN"
  else
    caddy start --adapter caddyfile --config "$CADDYFILE" --pidfile "$PIDFILE" >/dev/null 2>&1
    echo "router started on $LISTEN (admin $ADMIN)"
  fi
}

cmd_stop() {
  admin_alive && caddy stop --address "$ADMIN" >/dev/null 2>&1 || true
  [ -f "$PIDFILE" ] && rm -f "$PIDFILE"
  echo "router stopped"
}

cmd_status() {
  if admin_alive; then
    echo "router: running on $LISTEN (admin $ADMIN)"
    shopt -s nullglob
    local f
    for f in "$INST_DIR"/*.json; do
      record_active "$f" || continue
      local sock; sock="$(json_get "$f" socket)"
      printf '  %s.%s -> %s\n' "$(json_get "$f" id)" "$DOMAIN" \
        "${sock:+unix/$sock}${sock:-127.0.0.1:$(json_get "$f" port)}"
    done
  else
    echo "router: not running"
  fi
}

case "${1:-}" in
  reload) cmd_reload;;
  stop)   cmd_stop;;
  status) cmd_status;;
  config) generate; cat "$CADDYFILE";;
  *) echo "usage: $0 {reload|stop|status|config}" >&2; exit 2;;
esac
