defmodule Mob.Dev do
  @moduledoc """
  Safe, reproducible development tooling for Mob.

  ## Principles

    * **No default cookie.** The cookie is read from config (sourced from the
      gitignored `.env.dev`). If it is missing, we raise — we never fall back to
      a constant, because a known cookie on a distributed node is RCE.
    * **Dev-only distribution.** Distribution is started explicitly from a dev
      entrypoint, not unconditionally from `Application.start/2`. In a release,
      prefer setting node/cookie via `rel/env.sh` / `vm.args`.
    * **Loopback by default.** See `Mix.Tasks.Mob.Dev.Setup` for the networking
      and tunnel model.

  ## Wiring (dev only)

  Read config from the environment at runtime:

      # config/runtime.exs
      if config_env() == :dev do
        config :my_app, :mob_dev,
          node: System.fetch_env!("MOB_NODE"),
          cookie: System.fetch_env!("MOB_COOKIE")
      end

  Start distribution from a dev entrypoint (NOT from `Application.start/2`):

      # e.g. a `mix mob.dev` task, or a dev-only Mob.Dev.start/0
      Mob.Dev.ensure_distribution!()

  Supervise lifecycle in `Mob.Dev.Connection` — but only in dev:

      children =
        [Repo, MyAppWeb.Endpoint] ++
          if(Application.get_env(:my_app, :mob_dev), do: [Mob.Dev.Connection], else: [])
  """

  @doc """
  Starts distributed Erlang for dev using the configured node + cookie.

  Raises if the cookie is not configured — there is intentionally no default.
  Idempotent: a no-op if the node is already alive.
  """
  def ensure_distribution! do
    cfg = Application.get_env(:my_app, :mob_dev) || raise_unconfigured()

    node = cfg |> Keyword.fetch!(:node) |> to_string() |> String.to_atom()
    # fetch!/2 raises on a missing cookie — that is the point.
    cookie = cfg |> Keyword.fetch!(:cookie) |> normalize_cookie!()

    if Node.alive?() do
      :ok
    else
      case Node.start(node) do
        {:ok, _pid} ->
          Node.set_cookie(cookie)
          :ok

        {:error, reason} ->
          raise "Mob.Dev: could not start node #{inspect(node)}: #{inspect(reason)}"
      end
    end
  end

  defp normalize_cookie!(cookie) when is_atom(cookie), do: cookie

  defp normalize_cookie!(cookie) when is_binary(cookie) do
    if cookie == "" do
      raise "Mob.Dev: MOB_COOKIE is empty. Run `mix mob.dev.setup`."
    end

    # `Node.set_cookie/1` requires an atom. This converts exactly one trusted,
    # bounded value (the developer's own cookie from .env.dev) per VM boot — it
    # is NOT attacker-controlled and cannot exhaust the atom table, so the usual
    # String.to_atom/1 prohibition does not apply. binary_to_atom/1 makes that
    # single-shot, non-interning intent explicit.
    :erlang.binary_to_atom(cookie, :utf8)
  end

  defp raise_unconfigured do
    raise """
    Mob.Dev: :mob_dev is not configured.

    Distribution will NOT start without an explicit node + cookie. Run:

        mix mob.dev.setup

    and ensure config/runtime.exs reads MOB_NODE / MOB_COOKIE in dev.
    """
  end

  @doc false
  # Inlined so `mix mob.dev.setup` is self-contained. In a real package this
  # would live in priv/templates/dev-mobile.sh and be read with File.read!/1.
  def bin_script_template do
    ~S"""
    #!/usr/bin/env bash
    # bin/dev-mobile — one-command, safe, reproducible Mob dev connection.
    # Installed by `mix mob.dev.setup`. See Mix.Tasks.Mob.Dev.Setup for the
    # security + networking model.
    set -euo pipefail

    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
    cd "$PROJECT_ROOT"

    log()   { printf '\033[0;34m▶ %s\033[0m\n' "$*"; }
    warn()  { printf '\033[0;33m! %s\033[0m\n' "$*" >&2; }
    error() { printf '\033[0;31m✗ %s\033[0m\n' "$*" >&2; }

    ENV_FILE="$PROJECT_ROOT/.env.dev"
    if [[ ! -f "$ENV_FILE" ]]; then
      error ".env.dev not found. Run 'mix mob.dev.setup' first."
      exit 1
    fi

    # Source the env file. set -a exports everything it defines. This is shell
    # sourcing (not xargs word-splitting), so values are not mangled. The cookie
    # generated by mob.dev.setup is base32 [a-z2-7] — no quoting hazards. Treat
    # .env.dev as developer-owned (it is gitignored); do not source untrusted files.
    set -a
    # shellcheck disable=SC1090
    . "$ENV_FILE"
    set +a

    : "${MOB_NODE:?MOB_NODE not set in .env.dev — re-run mix mob.dev.setup}"
    : "${MOB_COOKIE:?MOB_COOKIE not set in .env.dev — re-run mix mob.dev.setup}"

    DEVICE="${1:-${MOB_DEFAULT_DEVICE:-emulator}}"
    log "Device: $DEVICE   Node: $MOB_NODE"

    # Start the hot-reload watcher in its OWN session/process group so we can
    # tear down the entire tree (mix wrapper + beam.smp) on exit — killing the
    # mix PID alone would orphan the BEAM.
    log "Starting hot-reload watcher (mix mob.dev)..."
    setsid mix mob.dev &          # ASSUMED MOB API: file watcher + hot pusher
    WATCHER_PGID=$!

    cleanup() {
      log "Stopping watcher process group..."
      kill -- -"$WATCHER_PGID" 2>/dev/null || true
      wait "$WATCHER_PGID" 2>/dev/null || true
    }
    trap cleanup EXIT INT TERM

    # Bail early if the watcher died on startup.
    sleep 0.5
    if ! kill -0 "$WATCHER_PGID" 2>/dev/null; then
      error "Watcher (mix mob.dev) exited immediately. Check its output above."
      exit 1
    fi

    # Bounded poll for device reachability instead of a blind sleep.
    log "Waiting for device/BEAM to become reachable..."
    reachable=0
    for _ in $(seq 1 30); do
      if mix mob.ping --device "$DEVICE" >/dev/null 2>&1; then   # ASSUMED MOB API
        reachable=1
        break
      fi
      # Also fail fast if the watcher died while we waited.
      if ! kill -0 "$WATCHER_PGID" 2>/dev/null; then
        error "Watcher exited while waiting for the device."
        exit 1
      fi
      sleep 1
    done

    if [[ "$reachable" -ne 1 ]]; then
      error "Timed out (30s) waiting for $DEVICE. Is the app running and tunnelled?"
      warn  "Physical device? Ensure your USB tunnel is up (adb forward / iproxy)."
      exit 1
    fi

    log "Connecting IEx to $DEVICE..."
    mix mob.connect --device "$DEVICE"   # ASSUMED MOB API: foreground IEx session
    # On exit, the trap tears the watcher group down.
    """
  end
end
