defmodule DevIDE.Runtimes do
  @moduledoc """
  Agent-worktree discovery + runtime status export for the workspace.

  This is a single-runtime service — it stores where agent work *has* run and,
  for worktree runtimes, starts the recorded preview server from that worktree.
  There is no host registry or multi-host placement: a workspace runs on the box
  serving this cockpit. Runtime preview launch commands are generated by DevIDE
  and validated against the recorded worktree cwd.

  Live surface today:

    * **Agent worktree discovery** — `observe_worktree/2` registers git
      worktrees agents create (via the `terminal_report_worktree` MCP tool).
    * **Status export** — `list_runtimes/1` / `get_runtime/1` snapshot runtimes
      for the read API and `Export.WorkspaceStatus`.
  """

  alias DevIDE.Git.Inspector, as: GitInspector

  alias DevIDE.Runtimes.{
    LifecycleEvent,
    PreviewLauncher,
    PreviewServer,
    Profile,
    Runtime,
    StateMachine
  }

  alias DevIDE.Terminals.Tmux
  alias DevIDE.Workspaces.State
  alias DevIDE.Workspaces.State.WorkspaceRecord

  @default_ttl_seconds 60 * 60

  @callback create_runtime(Runtime.t(), LifecycleEvent.t()) ::
              {:ok, Runtime.t()} | {:error, term()}
  @callback update_runtime(Runtime.t(), LifecycleEvent.t() | nil) ::
              {:ok, Runtime.t()} | {:error, term()}
  @callback get_runtime(String.t()) :: {:ok, Runtime.t()} | :error
  @callback list_runtimes(map()) :: [Runtime.t()]
  @callback list_runtimes_by_workspace_ids([String.t()]) :: [Runtime.t()]
  @callback events_for(String.t()) :: [LifecycleEvent.t()]
  @callback clear() :: :ok
  @optional_callbacks list_runtimes_by_workspace_ids: 1

  def list_runtimes(filters \\ %{}), do: impl().list_runtimes(normalize_filter(filters))

  @doc "List runtimes for several workspaces in one query, grouped by workspace id."
  @spec list_runtimes_by_workspace_ids([String.t()]) :: %{optional(String.t()) => [Runtime.t()]}
  def list_runtimes_by_workspace_ids(workspace_ids) when is_list(workspace_ids) do
    workspace_ids = Enum.filter(workspace_ids, &(is_binary(&1) and &1 != ""))

    adapter = impl()

    runtimes =
      if function_exported?(adapter, :list_runtimes_by_workspace_ids, 1) do
        adapter.list_runtimes_by_workspace_ids(workspace_ids)
      else
        adapter.list_runtimes(%{})
        |> Enum.filter(&(&1.workspace_id in workspace_ids))
      end

    runtimes
    |> Enum.group_by(& &1.workspace_id)
  end

  def get_runtime(runtime_id) when is_binary(runtime_id), do: impl().get_runtime(runtime_id)
  def get_runtime(_), do: :error

  @doc "Expire a runtime and append a lifecycle event."
  @spec expire_runtime(String.t(), map()) :: {:ok, Runtime.t()} | :error | {:error, term()}
  def expire_runtime(runtime_id, attrs \\ %{}) do
    transition_runtime(runtime_id, :expire, "runtime_expired", attrs, fn runtime ->
      now = datetime_value(attrs, "expired_at") || DateTime.utc_now()

      %{
        runtime
        | status: "expired",
          expired_at: now,
          failure_reason: string_value(attrs, "reason") || runtime.failure_reason,
          heartbeat_at: runtime.heartbeat_at || now
      }
    end)
  end

  @doc "Mark a runtime cleaned and append a lifecycle event."
  @spec cleanup_runtime(String.t(), map()) :: {:ok, Runtime.t()} | :error | {:error, term()}
  def cleanup_runtime(runtime_id, attrs \\ %{}) do
    transition_runtime(runtime_id, :cleanup, "runtime_cleaned", attrs, fn runtime ->
      now = datetime_value(attrs, "cleaned_at") || DateTime.utc_now()
      %{runtime | cleaned_at: now, active_assignments: 0}
    end)
  end

  @doc "Run a function while holding the shared lock for one runtime id."
  @spec with_runtime_lock(String.t(), (-> result)) :: result when result: term()
  def with_runtime_lock(runtime_id, fun)
      when is_binary(runtime_id) and is_function(fun, 0) do
    with_reentrant_global_lock({__MODULE__, :runtime, runtime_id}, fun)
  end

  @doc "Serialize preview-port selection and persistence across runtimes."
  @spec with_preview_port_lock((-> result)) :: result when result: term()
  def with_preview_port_lock(fun) when is_function(fun, 0) do
    with_reentrant_global_lock({__MODULE__, :preview_ports}, fun)
  end

  @doc "Restore an expired or cleaned runtime and append a lifecycle event."
  @spec restore_runtime(String.t(), map()) :: {:ok, Runtime.t()} | :error | {:error, term()}
  def restore_runtime(runtime_id, attrs \\ %{})

  def restore_runtime(runtime_id, attrs) when is_binary(runtime_id) and is_map(attrs) do
    with_runtime_lock(runtime_id, fn -> do_restore_runtime(runtime_id, attrs) end)
  end

  def restore_runtime(_runtime_id, _attrs), do: :error

  defp do_restore_runtime(runtime_id, attrs) do
    case get_runtime(runtime_id) do
      {:ok, %Runtime{status: "provisioned"} = runtime} ->
        {:ok, runtime}

      {:ok, %Runtime{}} ->
        transition_runtime(runtime_id, :restore, "runtime_restored", attrs, fn runtime ->
          now = datetime_value(attrs, "restored_at") || DateTime.utc_now()

          %{
            runtime
            | status: "provisioned",
              expired_at: nil,
              cleaned_at: nil,
              failure_reason: nil,
              active_assignments: 0,
              heartbeat_at: now
          }
        end)

      :error ->
        :error
    end
  end

  @doc "List active agent worktree runtimes for a workspace."
  @spec list_agent_worktrees(String.t()) :: [map()]
  def list_agent_worktrees(workspace_id) when is_binary(workspace_id) do
    %{"workspace_id" => workspace_id}
    |> list_runtimes()
    |> Enum.filter(&agent_worktree_runtime?/1)
    |> Enum.reject(&(&1.status in ["cleaned", "expired"]))
    |> Enum.map(&agent_worktree_payload/1)
  end

  def list_agent_worktrees(_workspace_id), do: []

  @doc """
  Observe an agent-created Git worktree as a child runtime of `workspace_id`.

  This is record-only: it never creates a manager workspace, starts Docker, or
  spawns a shell. The worktree is accepted when it lives under the workspace
  root, or when it lives under an allowed agent-worktree root and its Git common
  dir proves it belongs to a repo inside the parent workspace.
  """
  @spec observe_worktree(String.t(), map()) :: {:ok, Runtime.t()} | {:error, term()}
  def observe_worktree(workspace_id, attrs) when is_binary(workspace_id) and is_map(attrs) do
    with {:ok, %WorkspaceRecord{} = record} <- State.get(workspace_id),
         {:ok, worktree_path} <- observed_worktree_path(record, attrs),
         {:ok, %GitInspector{} = git_info} <- inspect_worktree(worktree_path),
         :ok <- validate_agent_worktree(record, worktree_path, git_info) do
      with_preview_port_lock(fn ->
        upsert_agent_worktree_runtime(record, attrs, worktree_path, git_info)
      end)
    end
  end

  def observe_worktree(_workspace_id, _attrs), do: {:error, :invalid_attrs}

  @doc """
  Reconcile Git-linked worktrees for a workspace home checkout.

  This discovers `git worktree list --porcelain` entries from the workspace
  root, records linked worktrees as agent-worktree runtimes, and expires prior
  Git-discovered records that no longer appear. Agent-reported runtimes are
  expired only once their worktree path no longer exists on disk.
  """
  @spec discover_worktrees(String.t()) ::
          {:ok, %{observed: [Runtime.t()], expired: [Runtime.t()], rejected: [map()]}}
          | {:error, term()}
  def discover_worktrees(workspace_id) when is_binary(workspace_id) do
    with {:ok, %WorkspaceRecord{host_path: root} = record} <- State.get(workspace_id),
         true <- git_checkout_root?(root),
         {:ok, entries} <- git_worktree_entries(root) do
      linked =
        Enum.reject(entries, fn entry ->
          same_path?(Map.get(entry, "worktree"), root)
        end)

      {observed, rejected} =
        Enum.reduce(linked, {[], []}, fn entry, {observed, rejected} ->
          worktree_path = Map.get(entry, "worktree")

          attrs = %{
            "worktree_path" => worktree_path,
            "branch" => Map.get(entry, "branch"),
            "source" => "git_discovery",
            "metadata" => %{"git_worktree_list" => true}
          }

          case observe_worktree(workspace_id, attrs) do
            {:ok, runtime} ->
              {[runtime | observed], rejected}

            {:error, reason} ->
              {observed, [%{path: worktree_path, reason: reason} | rejected]}
          end
        end)

      expired = expire_missing_worktrees(record.external_id, linked)

      {:ok,
       %{
         observed: Enum.reverse(observed),
         expired: expired,
         rejected: Enum.reverse(rejected)
       }}
    else
      false ->
        {:ok, %{observed: [], expired: [], rejected: []}}

      :error ->
        {:ok, %{observed: [], expired: [], rejected: []}}

      {:error, reason} ->
        {:error, reason}
    end
  end

  def discover_worktrees(_workspace_id), do: {:error, :invalid_workspace_id}

  def events_for(runtime_id) when is_binary(runtime_id), do: impl().events_for(runtime_id)
  def events_for(_), do: []

  def clear, do: impl().clear()

  @doc "Expire runtimes whose heartbeat/creation timestamp is older than their TTL."
  @spec expire_stale(DateTime.t(), keyword()) :: [Runtime.t()]
  def expire_stale(now \\ DateTime.utc_now(), opts \\ []) do
    ttl_seconds = Keyword.get(opts, :ttl_seconds, @default_ttl_seconds)

    %{}
    |> list_runtimes()
    |> Enum.filter(&stale?(&1, now, ttl_seconds))
    |> Enum.flat_map(fn runtime ->
      case expire_runtime(runtime.id, %{"reason" => "stale_runtime", "expired_at" => now}) do
        {:ok, expired} -> [expired]
        _ -> []
      end
    end)
  end

  @doc "Clean all currently expired runtimes."
  @spec cleanup_expired(DateTime.t(), keyword()) :: [Runtime.t()]
  def cleanup_expired(_now \\ DateTime.utc_now(), opts \\ []) do
    only_ids = only_runtime_ids(Keyword.get(opts, :only_ids))

    list_runtimes(%{"status" => "expired"})
    |> Enum.filter(fn runtime ->
      is_nil(only_ids) or MapSet.member?(only_ids, runtime.id)
    end)
    |> Enum.flat_map(fn runtime ->
      with_runtime_lock(runtime.id, fn ->
        case get_runtime(runtime.id) do
          {:ok, %Runtime{status: "expired"}} ->
            case cleanup_runtime(runtime.id) do
              {:ok, cleaned} -> [cleaned]
              _ -> []
            end

          _ ->
            []
        end
      end)
    end)
  end

  defp only_runtime_ids(nil), do: nil

  defp only_runtime_ids(ids) when is_list(ids) do
    ids = Enum.filter(ids, &is_binary/1)
    if ids == [], do: nil, else: MapSet.new(ids)
  end

  @doc "Add current runtime projection to assignment metadata for read surfaces."
  def decorate_assignment_metadata(metadata) when is_map(metadata) do
    case runtime_id_from_metadata(metadata) do
      nil ->
        metadata

      runtime_id ->
        case get_runtime(runtime_id) do
          {:ok, %Runtime{} = runtime} -> put_runtime_metadata(metadata, runtime)
          :error -> metadata
        end
    end
  end

  def decorate_assignment_metadata(metadata), do: metadata

  def runtime_id_from_metadata(metadata) when is_map(metadata) do
    runtime = Map.get(metadata, "runtime") || Map.get(metadata, :runtime) || %{}

    string_value(runtime, "id") ||
      string_value(runtime, "runtime_id") ||
      string_value(metadata, "runtime_id") ||
      string_value(metadata, "runtime")
  end

  def runtime_id_from_metadata(_), do: nil

  def payload(%Runtime{} = runtime) do
    %{
      id: runtime.id,
      workspace_id: runtime.workspace_id,
      host: runtime.host_id,
      os: runtime.os,
      repo: runtime.repo,
      branch: runtime.branch,
      worktree_path: runtime.worktree_path,
      runner_id: runtime.runner_id,
      session_id: runtime.session_id,
      tmux_session_id: runtime.tmux_session_id,
      isolation_mode: runtime.isolation_mode,
      status: runtime.status,
      capabilities: runtime.capabilities,
      tools: runtime.tools,
      concurrency_limit: runtime.concurrency_limit,
      active_assignments: runtime.active_assignments,
      created_at: iso(runtime.created_at),
      heartbeat_at: iso(runtime.heartbeat_at),
      expired_at: iso(runtime.expired_at),
      cleaned_at: iso(runtime.cleaned_at),
      failure_reason: runtime.failure_reason,
      preview_server: runtime_preview_server(runtime),
      runtime_profile: Profile.for_runtime(runtime),
      preview_surfaces: runtime_preview_surfaces(runtime),
      metadata: runtime.metadata || %{}
    }
  end

  @doc "Return the normalized runtime profile stored on a runtime, if any."
  @spec runtime_profile(Runtime.t()) :: map() | nil
  def runtime_profile(%Runtime{} = runtime), do: Profile.for_runtime(runtime)

  @doc "Return the runtime-scoped preview server record stored on a runtime, if present."
  @spec runtime_preview_server(Runtime.t()) :: map() | nil
  def runtime_preview_server(%Runtime{} = runtime),
    do: PreviewServer.for_metadata(runtime.metadata)

  @doc "Return preview surface descriptors derived from a runtime profile."
  @spec runtime_preview_surfaces(Runtime.t()) :: [map()]
  def runtime_preview_surfaces(%Runtime{} = runtime), do: Profile.preview_surfaces(runtime)

  @doc "Update the runtime-owned preview server status without changing runtime ownership."
  @spec mark_preview_server(Runtime.t(), String.t(), String.t() | nil) ::
          {:ok, Runtime.t()} | {:error, term()}
  def mark_preview_server(runtime, status, failure_reason \\ nil)

  def mark_preview_server(%Runtime{} = runtime, status, failure_reason)
      when is_binary(status) do
    metadata = PreviewServer.put_status(runtime.metadata || %{}, status, failure_reason)
    runtime = %{runtime | metadata: metadata, heartbeat_at: DateTime.utc_now()}

    result =
      impl().update_runtime(
        runtime,
        event(runtime, runtime.status, "runtime_preview_#{status}",
          metadata:
            %{
              "preview_server_id" =>
                runtime.metadata
                |> PreviewServer.for_metadata()
                |> case do
                  %{} = server -> server["id"]
                  _ -> nil
                end,
              "preview_status" => status,
              "failure_reason" => failure_reason
            }
            |> Enum.reject(fn {_key, value} -> is_nil(value) end)
            |> Map.new()
        )
      )

    if status == "failed", do: publish_preview_failure(runtime, failure_reason)
    result
  end

  def mark_preview_server(_, _, _), do: {:error, :invalid_runtime}

  def event_payload(%LifecycleEvent{} = event) do
    %{
      id: event.id,
      runtime_id: event.runtime_id,
      workspace_id: event.workspace_id,
      event: event.event,
      from_status: event.from_status,
      to_status: event.to_status,
      actor_id: event.actor_id,
      assignment_id: event.assignment_id,
      runner_id: event.runner_id,
      metadata: event.metadata || %{},
      inserted_at: iso(event.inserted_at)
    }
  end

  def project_lifecycle(events), do: StateMachine.reduce(events)

  defp observed_worktree_path(%WorkspaceRecord{host_path: nil}, _attrs),
    do: {:error, :workspace_root_unavailable}

  defp observed_worktree_path(%WorkspaceRecord{host_path: root}, attrs) do
    case string_value(attrs, "worktree_path") || string_value(attrs, "runtime_path") ||
           string_value(attrs, "path") do
      nil ->
        {:error, :worktree_path_required}

      requested ->
        path = expand_observed_path(root, requested)

        if File.dir?(path), do: {:ok, path}, else: {:error, :worktree_not_found}
    end
  end

  defp expand_observed_path(root, path) do
    case Path.type(path) do
      :absolute -> Path.expand(path)
      _ -> Path.expand(path, root)
    end
  end

  defp inspect_worktree(path) do
    case GitInspector.inspect_cwd(path) do
      {:ok, info} -> {:ok, info}
      :error -> {:error, :not_git_worktree}
    end
  end

  defp validate_agent_worktree(
         %WorkspaceRecord{host_path: root} = record,
         path,
         %GitInspector{} = info
       ) do
    with :ok <- reject_main_checkout(root, path, info) do
      cond do
        under_root?(path, root) ->
          :ok

        under_agent_worktree_root?(path) and related_to_workspace_git?(record, info) ->
          :ok

        under_agent_worktree_root?(path) ->
          {:error, :unrelated_worktree}

        true ->
          {:error, :worktree_outside_allowed_roots}
      end
    end
  end

  defp reject_main_checkout(root, path, %GitInspector{} = info) do
    if same_path?(Path.expand(root), Path.expand(path)) and info.worktree? == false do
      {:error,
       %{
         error: :main_checkout_not_allowed,
         message: "Report a dedicated git worktree path, not the workspace main checkout.",
         worktree_path: path
       }}
    else
      :ok
    end
  end

  defp related_to_workspace_git?(%WorkspaceRecord{host_path: root}, %GitInspector{} = info) do
    git_common_dir = clean_optional_path(info.git_common_dir)
    root = Path.expand(root)

    cond do
      is_binary(git_common_dir) and under_root?(git_common_dir, root) ->
        true

      true ->
        case GitInspector.inspect_cwd(root) do
          {:ok, parent} -> same_path?(parent.git_common_dir, git_common_dir)
          :error -> false
        end
    end
  end

  defp upsert_agent_worktree_runtime(
         %WorkspaceRecord{} = record,
         attrs,
         worktree_path,
         %GitInspector{} = git_info
       ) do
    existing = existing_agent_worktree_runtime(record.external_id, worktree_path, attrs)

    runtime_id =
      string_value(attrs, "runtime_id") || (existing && existing.id) || worktree_runtime_id()

    now = datetime_value(attrs, "heartbeat_at") || DateTime.utc_now()

    existing_metadata = (existing && existing.metadata) || %{}

    tmux_session_id =
      string_value(attrs, "tmux_session_id") || (existing && existing.tmux_session_id) ||
        Tmux.session_name(record.name || record.external_id, runtime_id)

    metadata =
      existing_metadata
      |> Map.merge(map_value(attrs, "metadata"))
      |> Map.merge(
        agent_worktree_metadata(attrs, existing_metadata, worktree_path, git_info, now)
      )

    with {:ok, metadata} <-
           put_worktree_preview_metadata(
             record,
             runtime_id,
             tmux_session_id,
             worktree_path,
             attrs,
             metadata,
             existing
           ) do
      runtime = %Runtime{
        id: runtime_id,
        workspace_id: record.external_id,
        host_id:
          string_value(attrs, "host_id") || string_value(attrs, "host") ||
            ((existing && existing.host_id) || "local"),
        os: string_value(attrs, "os") || (existing && existing.os),
        repo:
          string_value(attrs, "repo") || (existing && existing.repo) ||
            Path.basename(git_info.toplevel),
        branch: string_value(attrs, "branch") || git_info.branch || (existing && existing.branch),
        worktree_path: worktree_path,
        runner_id: string_value(attrs, "runner_id") || (existing && existing.runner_id),
        session_id: string_value(attrs, "session_id") || (existing && existing.session_id),
        tmux_session_id: tmux_session_id,
        isolation_mode: "worktree",
        status:
          string_value(attrs, "runtime_status") || (existing && existing.status) ||
            "provisioned",
        capabilities:
          Enum.uniq(
            ((existing && existing.capabilities) || []) ++ string_list(attrs, "capabilities")
          ),
        tools: Enum.uniq(((existing && existing.tools) || []) ++ string_list(attrs, "tools")),
        concurrency_limit:
          positive_integer(
            attrs,
            "concurrency_limit",
            (existing && existing.concurrency_limit) || 1
          ),
        active_assignments: (existing && existing.active_assignments) || 0,
        created_at: (existing && existing.created_at) || now,
        heartbeat_at: now,
        metadata: metadata
      }

      event_metadata = Map.take(metadata, ["agent", "branch", "git_common_dir", "worktree_path"])

      # Single create OR single update — never create(status=requested) then
      # update(status=provisioned). The two-step path raced/failed with
      # Ecto.NoResultsError in update_runtime/2 after create appeared to succeed
      # (artifact worktree on disk, no runtime row), breaking artifact_create.
      result =
        if existing do
          impl().update_runtime(
            runtime,
            event(runtime, existing.status, "runtime_heartbeat",
              actor_id: string_value(attrs, "actor_id"),
              runner_id: string_value(attrs, "runner_id"),
              metadata: event_metadata
            )
          )
        else
          impl().create_runtime(
            runtime,
            event(runtime, nil, "runtime_provisioned",
              actor_id: string_value(attrs, "actor_id"),
              runner_id: string_value(attrs, "runner_id"),
              metadata: event_metadata
            )
          )
        end

      with {:ok, %Runtime{} = runtime} <- result do
        if preview_start_requested?(attrs), do: PreviewLauncher.ensure_started(runtime)
        {:ok, runtime}
      end
    end
  end

  defp put_worktree_preview_metadata(
         %WorkspaceRecord{} = record,
         runtime_id,
         tmux_session_id,
         worktree_path,
         attrs,
         metadata,
         existing
       ) do
    existing_server = existing && PreviewServer.for_metadata(existing.metadata || %{})

    allow_occupied_port? =
      match?(%Runtime{status: "provisioned"}, existing) or
        (match?(%Runtime{status: "expired"}, existing) and
           PreviewServer.owns_live_port?(existing_server))

    preview_attrs =
      attrs
      |> Map.put("metadata", metadata)
      |> Map.put("_allow_occupied_preview_port", allow_occupied_port?)

    case PreviewServer.build_for_worktree(
           record,
           runtime_id,
           tmux_session_id,
           worktree_path,
           preview_attrs,
           used_preview_ports(runtime_id)
         ) do
      {:ok, preview_server} ->
        {:ok, PreviewServer.put_profile(metadata, preview_server)}

      {:error, :no_runtime_preview_port_available} ->
        {:ok, PreviewServer.put_unavailable(metadata, "no_runtime_preview_port_available")}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp used_preview_ports(runtime_id) do
    list_runtimes(%{})
    |> Enum.reject(&(&1.id == runtime_id))
    |> Enum.reject(&(&1.status in ["cleaned", "expired"]))
    |> Enum.flat_map(fn %Runtime{metadata: metadata} ->
      PreviewServer.metadata_ports(metadata)
    end)
    |> Enum.uniq()
  end

  defp existing_agent_worktree_runtime(workspace_id, worktree_path, attrs) do
    runtime_id = string_value(attrs, "runtime_id")

    runtime_by_id =
      case runtime_id && get_runtime(runtime_id) do
        {:ok, %Runtime{} = runtime} -> runtime
        _ -> nil
      end

    cond do
      runtime_by_id && runtime_by_id.workspace_id == workspace_id &&
          agent_worktree_runtime?(runtime_by_id) ->
        runtime_by_id

      true ->
        list_runtimes(%{"workspace_id" => workspace_id})
        |> Enum.find(fn runtime ->
          agent_worktree_runtime?(runtime) and runtime.status not in ["cleaned", "expired"] and
            same_path?(runtime.worktree_path, worktree_path)
        end)
    end
  end

  defp git_checkout_root?(root) when is_binary(root) do
    File.exists?(Path.join(root, ".git")) and
      match?({:ok, %GitInspector{}}, GitInspector.inspect_cwd(root))
  end

  defp git_checkout_root?(_root), do: false

  defp git_worktree_entries(root) do
    case System.cmd("git", ["-C", root, "worktree", "list", "--porcelain"],
           stderr_to_stdout: true
         ) do
      {output, 0} ->
        {:ok, parse_worktree_porcelain(output)}

      {output, status} ->
        {:error, {:git_worktree_list_failed, status, String.trim(output)}}
    end
  rescue
    error -> {:error, {:git_worktree_list_failed, Exception.message(error)}}
  end

  defp parse_worktree_porcelain(output) when is_binary(output) do
    output
    |> String.split(~r/\n\s*\n/, trim: true)
    |> Enum.map(&parse_worktree_record/1)
    |> Enum.filter(&Map.has_key?(&1, "worktree"))
  end

  defp parse_worktree_record(record) do
    record
    |> String.split("\n", trim: true)
    |> Enum.reduce(%{}, fn line, acc ->
      case String.split(line, " ", parts: 2) do
        ["branch", ref] ->
          Map.put(acc, "branch", String.replace_prefix(ref, "refs/heads/", ""))

        [key, value] ->
          Map.put(acc, key, value)

        [flag] ->
          Map.put(acc, flag, true)
      end
    end)
  end

  defp expire_missing_worktrees(workspace_id, linked_entries) do
    linked_paths =
      linked_entries
      |> Enum.map(&Map.get(&1, "worktree"))
      |> Enum.filter(&is_binary/1)
      |> Enum.map(&Path.expand/1)
      |> MapSet.new()

    %{"workspace_id" => workspace_id}
    |> list_runtimes()
    |> Enum.filter(&missing_worktree?(&1, linked_paths))
    |> Enum.reduce([], fn runtime, expired ->
      now = DateTime.utc_now()
      metadata = Map.put(runtime.metadata || %{}, "expired_by", "git_discovery")

      updated = %{
        runtime
        | status: "expired",
          expired_at: now,
          heartbeat_at: now,
          metadata: metadata
      }

      case impl().update_runtime(
             updated,
             event(updated, runtime.status, "runtime_expired",
               metadata: %{"reason" => missing_worktree_reason(runtime)}
             )
           ) do
        {:ok, expired_runtime} -> [expired_runtime | expired]
        _ -> expired
      end
    end)
    |> Enum.reverse()
  end

  # Git-discovered records expire as soon as `git worktree list` stops naming
  # them. Agent-reported records are owned by the agent while their directory
  # exists; once the path is gone from disk there is nothing left to reattach
  # to, so they expire too instead of lingering in session directories.
  defp missing_worktree?(%Runtime{} = runtime, linked_paths) do
    metadata = runtime.metadata || %{}
    path = runtime.worktree_path || Map.get(metadata, "worktree_path")

    agent_worktree_runtime?(runtime) and runtime.status not in ["cleaned", "expired"] and
      is_binary(path) and
      not MapSet.member?(linked_paths, Path.expand(path)) and
      (Map.get(metadata, "source") == "git_discovery" or not File.dir?(path))
  end

  defp missing_worktree_reason(%Runtime{metadata: metadata}) do
    if Map.get(metadata || %{}, "source") == "git_discovery" do
      "git_worktree_missing"
    else
      "worktree_path_missing"
    end
  end

  defp agent_worktree_metadata(
         attrs,
         existing_metadata,
         worktree_path,
         %GitInspector{} = git_info,
         observed_at
       ) do
    dirty_count = dirty_count(worktree_path)
    branch = string_value(attrs, "branch") || git_info.branch
    requested_source = string_value(attrs, "source")
    existing_source = Map.get(existing_metadata || %{}, "source")

    exit_status = string_value(attrs, "exit_status") || Map.get(existing_metadata, "exit_status")
    handoff = string_value(attrs, "handoff") || Map.get(existing_metadata, "handoff")

    %{
      "kind" => "agent_worktree",
      "provisioning_model" => "agent_worktree",
      "source" => agent_worktree_source(requested_source, existing_source),
      "agent" => string_value(attrs, "agent") || git_info.agent,
      "branch" => branch,
      "worktree_path" => worktree_path,
      "git_toplevel" => git_info.toplevel,
      "git_common_dir" => git_info.git_common_dir,
      "git_head_sha" => git_info.head_sha,
      "git_worktree" => git_info.worktree?,
      "git_detached" => git_info.detached?,
      "upstream" => git_info.upstream,
      "ahead" => git_info.ahead,
      "behind" => git_info.behind,
      "dirty_count" => dirty_count,
      "worktree_status" => if(dirty_count == 0, do: "clean", else: "dirty"),
      "observed_at" => DateTime.to_iso8601(observed_at),
      "exit_status" => exit_status,
      "handoff" => handoff,
      "exit_reported_at" => exit_reported_at(exit_status, handoff, existing_metadata, observed_at)
    }
    |> Enum.reject(fn {_key, value} -> value in [nil, ""] end)
    |> Map.new()
  end

  defp agent_worktree_source("git_discovery", source)
       when is_binary(source) and source not in ["", "git_discovery"],
       do: source

  defp agent_worktree_source(source, _existing_source) when is_binary(source) and source != "",
    do: source

  defp agent_worktree_source(nil, "git_discovery"), do: "agent_report"

  defp agent_worktree_source(nil, source) when is_binary(source) and source != "", do: source

  defp agent_worktree_source(_source, _existing_source), do: "agent_report"

  defp exit_reported_at(nil, nil, _existing_metadata, _observed_at), do: nil

  defp exit_reported_at(exit_status, handoff, existing_metadata, observed_at) do
    prior_exit = Map.get(existing_metadata || %{}, "exit_status")
    prior_handoff = Map.get(existing_metadata || %{}, "handoff")

    if exit_status != prior_exit or handoff != prior_handoff do
      DateTime.to_iso8601(observed_at)
    else
      Map.get(existing_metadata || %{}, "exit_reported_at")
    end
  end

  defp agent_worktree_runtime?(%Runtime{metadata: metadata}) when is_map(metadata) do
    Map.get(metadata, "kind") == "agent_worktree" or
      Map.get(metadata, "provisioning_model") == "agent_worktree"
  end

  defp agent_worktree_runtime?(_runtime), do: false

  defp agent_worktree_payload(%Runtime{} = runtime) do
    metadata = runtime.metadata || %{}
    path = runtime.worktree_path || Map.get(metadata, "worktree_path")

    %{
      runtime_id: runtime.id,
      workspace_id: runtime.workspace_id,
      path: path,
      path_label: path_label(path),
      branch: runtime.branch || Map.get(metadata, "branch"),
      tmux_session_id: runtime.tmux_session_id,
      git_toplevel: Map.get(metadata, "git_toplevel") || path,
      git_common_dir: Map.get(metadata, "git_common_dir"),
      git_head_sha: Map.get(metadata, "git_head_sha"),
      git_detached?: Map.get(metadata, "git_detached"),
      upstream: Map.get(metadata, "upstream"),
      ahead: Map.get(metadata, "ahead"),
      behind: Map.get(metadata, "behind"),
      agent: Map.get(metadata, "agent"),
      source: Map.get(metadata, "source"),
      worktree_status: Map.get(metadata, "worktree_status"),
      dirty_count: Map.get(metadata, "dirty_count"),
      exit_status: Map.get(metadata, "exit_status"),
      handoff: Map.get(metadata, "handoff"),
      observed_at: Map.get(metadata, "observed_at")
    }
    |> Enum.reject(fn {_key, value} -> value in [nil, ""] end)
    |> Map.new()
  end

  defp path_label(path) when is_binary(path) and path != "", do: Path.basename(path)
  defp path_label(_path), do: nil

  defp dirty_count(path) do
    case DevIDE.Git.status_short(path) do
      {:ok, entries} -> length(entries)
      _ -> nil
    end
  end

  defp worktree_runtime_id, do: "wt-" <> Ecto.UUID.generate()

  defp preview_start_requested?(attrs) do
    value =
      case Map.fetch(attrs, "ensure_preview_started") do
        {:ok, value} -> value
        :error -> Map.get(attrs, :ensure_preview_started)
      end

    value not in [false, "false", 0, "0"]
  end

  # :global's requester id makes nested acquisitions by the same process look
  # reentrant, but the inner release also drops the outer lock. Track depth in
  # the process dictionary so only the outermost call touches :global.
  defp with_reentrant_global_lock(resource, fun) do
    depth_key = {__MODULE__, :global_lock_depth, resource}

    case Process.get(depth_key, 0) do
      0 ->
        :global.trans({resource, self()}, fn ->
          Process.put(depth_key, 1)

          try do
            fun.()
          after
            Process.delete(depth_key)
          end
        end)

      depth ->
        Process.put(depth_key, depth + 1)

        try do
          fun.()
        after
          Process.put(depth_key, depth)
        end
    end
  end

  defp under_agent_worktree_root?(path) do
    roots =
      Application.get_env(:dev_ide, :agent_worktree_roots, []) ++
        configured_artifact_project_roots() ++
        env_agent_worktree_roots() ++ default_agent_worktree_roots()

    path = Path.expand(path)
    Enum.any?(roots, &under_root?(path, &1))
  end

  defp configured_artifact_project_roots do
    case Application.get_env(:dev_ide, :artifact_projects_root) do
      root when is_binary(root) and root != "" -> [root]
      _ -> []
    end
  end

  defp default_agent_worktree_roots do
    [
      Path.join(System.tmp_dir!(), "devide-agent-worktrees"),
      Path.expand("~/.local/share/opencode"),
      Path.expand("~/.local/share/codex"),
      Path.expand("~/.cache/codex"),
      Path.expand("~/.claude")
    ]
  end

  defp env_agent_worktree_roots do
    case System.get_env("DEV_IDE_AGENT_WORKTREE_ROOTS") do
      nil -> []
      value -> String.split(value, [",", ":"], trim: true)
    end
  end

  defp under_root?(path, root) when is_binary(path) and is_binary(root) do
    path = Path.expand(path)
    root = Path.expand(root)
    rel = Path.relative_to(path, root)
    rel != path and not String.starts_with?(rel, "..")
  end

  defp under_root?(_, _), do: false

  defp same_path?(left, right) when is_binary(left) and is_binary(right),
    do: Path.expand(left) == Path.expand(right)

  defp same_path?(_, _), do: false

  defp clean_optional_path(path) when is_binary(path) and path != "", do: Path.expand(path)
  defp clean_optional_path(_), do: nil

  defp put_runtime_metadata(metadata, %Runtime{} = runtime) do
    routing = Map.get(metadata, "routing") || Map.get(metadata, :routing) || %{}

    runtime_map =
      %{
        "id" => runtime.id,
        "runtime_id" => runtime.id,
        "runtime_path" => runtime.worktree_path,
        "worktree_path" => runtime.worktree_path,
        "host" => runtime.host_id,
        "os" => runtime.os,
        "repo" => runtime.repo,
        "branch" => runtime.branch,
        "branch_isolation" => runtime.isolation_mode,
        "isolation_mode" => runtime.isolation_mode,
        "runner_id" => runtime.runner_id,
        "session_id" => runtime.session_id,
        "tmux_session_id" => runtime.tmux_session_id,
        "status" => runtime.status,
        "active_assignments" => runtime.active_assignments,
        "concurrency_limit" => runtime.concurrency_limit
      }
      |> put_profile(Profile.for_runtime(runtime))
      |> Enum.reject(fn {_key, value} -> value in [nil, "", []] end)
      |> Map.new()

    required_tools =
      Map.get(runtime.metadata || %{}, "required_tools") ||
        Map.get(runtime.metadata || %{}, :required_tools) ||
        runtime.tools

    routing =
      routing
      |> Map.merge(%{
        "host" => runtime.host_id,
        "os" => runtime.os,
        "repo" => runtime.repo,
        "branch_isolation" => runtime.isolation_mode,
        "runtime_id" => runtime.id,
        "runtime_path" => runtime.worktree_path,
        "tools" => required_tools
      })
      |> Enum.reject(fn {_key, value} -> value in [nil, "", []] end)
      |> Map.new()

    metadata
    |> Map.put("runtime", runtime_map)
    |> Map.put("runtime_id", runtime.id)
    |> Map.put("runtime_path", runtime.worktree_path)
    |> Map.put("routing", routing)
  end

  defp publish_preview_failure(%Runtime{} = runtime, failure_reason) do
    preview_server = PreviewServer.for_metadata(runtime.metadata)

    DevIDE.Signals.Publish.domain_event(
      "runtime.preview_failed",
      %{
        runtime_id: runtime.id,
        workspace_id: runtime.workspace_id,
        preview_server_id: preview_server && preview_server["id"],
        preview_status: "failed",
        failure_reason: failure_reason,
        worktree_path: runtime.worktree_path
      },
      workspace_id: runtime.workspace_id,
      subject: runtime.id
    )
  end

  defp transition_runtime(runtime_id, transition, event_name, attrs, updater) do
    with {:ok, runtime} <- get_runtime(runtime_id),
         {:ok, next_status} <- StateMachine.transition(runtime.status, transition) do
      updated =
        runtime
        |> updater.()
        |> Map.put(:status, next_status)

      impl().update_runtime(
        updated,
        event(updated, runtime.status, event_name,
          actor_id: string_value(attrs, "actor_id"),
          assignment_id: string_value(attrs, "assignment_id"),
          runner_id: string_value(attrs, "runner_id"),
          metadata:
            %{
              "reason" => string_value(attrs, "reason")
            }
            |> Enum.reject(fn {_key, value} -> value in [nil, ""] end)
            |> Map.new()
        )
      )
    end
  end

  defp event(%Runtime{} = runtime, from_status, event, opts) do
    %LifecycleEvent{
      id: Ecto.UUID.generate(),
      runtime_id: runtime.id,
      workspace_id: runtime.workspace_id,
      event: event,
      from_status: from_status,
      to_status: runtime.status,
      actor_id: Keyword.get(opts, :actor_id),
      assignment_id: Keyword.get(opts, :assignment_id),
      runner_id: Keyword.get(opts, :runner_id),
      metadata: Keyword.get(opts, :metadata, %{}) || %{},
      inserted_at: DateTime.utc_now()
    }
  end

  defp stale?(%Runtime{status: status}, _now, _ttl_seconds)
       when status in ["expired", "cleaned"],
       do: false

  defp stale?(%Runtime{} = runtime, now, ttl_seconds) do
    last_seen = runtime.heartbeat_at || runtime.created_at
    last_seen && DateTime.compare(DateTime.add(last_seen, ttl_seconds, :second), now) != :gt
  end

  defp normalize_filter(filters) when is_map(filters) do
    filters
    |> Enum.map(fn {key, value} -> {to_string(key), value} end)
    |> Enum.reject(fn {_key, value} -> value in [nil, "", []] end)
    |> Map.new()
  end

  defp normalize_filter(_), do: %{}

  defp string_value(attrs, key) when is_map(attrs) do
    case DevIDE.PayloadAttrs.get(attrs, key) do
      value when is_binary(value) -> String.trim(value)
      _ -> nil
    end
  end

  defp string_value(_, _), do: nil

  defp string_list(attrs, key) when is_map(attrs) do
    case DevIDE.PayloadAttrs.get(attrs, key) do
      values when is_list(values) ->
        values
        |> Enum.filter(&is_binary/1)
        |> Enum.map(&String.trim/1)
        |> Enum.reject(&(&1 == ""))
        |> Enum.uniq()

      _ ->
        []
    end
  end

  defp positive_integer(attrs, key, fallback) when is_map(attrs) do
    value = DevIDE.PayloadAttrs.get(attrs, key)

    parsed =
      cond do
        is_integer(value) -> value
        is_binary(value) -> parse_int(value, fallback)
        true -> fallback
      end

    max(parsed, 1)
  end

  defp parse_int(value, fallback) do
    case Integer.parse(value) do
      {int, ""} -> int
      _ -> fallback
    end
  end

  defp datetime_value(attrs, key) when is_map(attrs) do
    case DevIDE.PayloadAttrs.get(attrs, key) do
      %DateTime{} = dt ->
        dt

      value when is_binary(value) ->
        case DateTime.from_iso8601(value) do
          {:ok, dt, _offset} -> dt
          _ -> nil
        end

      _ ->
        nil
    end
  end

  defp datetime_value(_, _), do: nil

  defp map_value(attrs, key) when is_map(attrs) do
    case DevIDE.PayloadAttrs.get(attrs, key) do
      value when is_map(value) -> value
      _ -> %{}
    end
  end

  defp map_value(_, _), do: %{}

  defp put_profile(metadata, nil), do: metadata

  defp put_profile(metadata, profile) when is_map(metadata) and is_map(profile),
    do: Map.put(metadata, "runtime_profile", profile)

  defp iso(nil), do: nil
  defp iso(%DateTime{} = dt), do: DateTime.to_iso8601(dt)

  defp impl,
    do:
      Application.get_env(
        :dev_ide,
        :runtimes_adapter,
        DevIDE.Runtimes.MemoryAdapter
      )
end
